### ISSUE TITLE
master-test.sh problems with automated installer.

### ISSUE THREAD

**Issue by arq5x** [arq5x/gemini#144]
Michael Heuer has reported issues running the master-test.sh suite after auto-installing.  He gets a seg fault with gemini when running the tests, and it looks like, on his system, the bottle.py "already loaded" messages are back.  This makes me think that there is somehow a conflict between the recently-installed gemini and some other version on his system.  trying to reproduce the error on one of our machines.

https://groups.google.com/forum/?fromgroups#!topic/gemini-variation/M8az4_Ue86I

**Comment by vivek2007** [comment]
Hi Aaron I am getting same error here

[root@localhost ~]# gemini load -v test/test2.snpeff.vcf test2.snpeff.db
CADD scores are being loaded (to skip use:--skip-cadd).
GERP per bp is being loaded (to skip use:--skip-gerp-bp).
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1117, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 183, in load_fn
    gemini_load.load(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 52, in load
    load_singlecore(args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 62, in load_singlecore
    gemini_loader = GeminiLoader(args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 63, in __init__
    self.vcf_reader = self._get_vcf_reader()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 217, in _get_vcf_reader
    return vcf.VCFReader(open(self.args.vcf), 'rb')
IOError: [Errno 2] No such file or directory: 'test/test2.snpeff.vcf'
