### ISSUE TITLE
gemini load fails when SnpEff is run with -sequenceOntolgy command line parameter

### ISSUE THREAD

**Issue by heuermh** [arq5x/gemini#215]
Somewhat related to issue #207, if you provide the -sequenceOntolgy (yes it is misspelled) command line parameter to SnpEff to have it emit Sequence Ontology terms for effects, the load step in GEMINI fails

``` bash
$ gemini load -v foo.eff-so.vcf -t snpEff foo.eff-so.vcf.db
Requested GEMINI database (foo.eff-so.vcf.db) not found. Please confirm the provided filename.
Traceback (most recent call last):
  File "/usr/bin/gemini", line 5, in <module>
    gemini.gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 612, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 31, in load
    load_singlecore(args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 40, in load_singlecore
    gemini_loader.populate_from_vcf()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 85, in populate_from_vcf
    (variant, variant_impacts) = self._prepare_variation(var)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 259, in _prepare_variation
    impacts = func_impact.interpret_impact(self.args, var)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/func_impact.py", line 43, in interpret_impact
    impact_info = snpEff.effect_map[impact_string]
KeyError: 'intergenic_region'
```

**Comment by RatnamRaju** [comment]
[root@localhost home]# gemini -v
Traceback (most recent call last):
  File "/usr/bin/gemini", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2659, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: numexpr>=2.4.3
