### ISSUE TITLE
LOF_sieve

### ISSUE THREAD

**Issue by ghost** [arq5x/gemini#354]
I am running gemini 0.11.0a.  When I run the gemini lof_sieve or gemini lof_interactions it throws a ton of errors.  the comp_het, AR, and AD, and burden work fine.  Had them work fine on previous versions.
My vcf was annotated using snpeff 3.6.
Thanks

Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 5, in <module>
    pkg_resources.run_script('gemini==0.11.0a', 'gemini')
  File "/usr/local/lib/python2.7/site-packages/setuptools-2.1-py2.7.egg/pkg_resources.py", line 488, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/setuptools-2.1-py2.7.egg/pkg_resources.py", line 1338, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/gemini-0.11.0a-py2.7.egg/EGG-INFO/scripts/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/usr/local/lib/python2.7/site-packages/gemini-0.11.0a-py2.7.egg/gemini/gemini_main.py", line 1099, in main
    args.func(parser, args)
  File "/usr/local/lib/python2.7/site-packages/gemini-0.11.0a-py2.7.egg/gemini/gemini_main.py", line 638, in lof_sieve_fn
    tool_lof_sieve.lof_sieve(parser, args)
  File "/usr/local/lib/python2.7/site-packages/gemini-0.11.0a-py2.7.egg/gemini/tool_lof_sieve.py", line 80, in lof_sieve
    get_ind_lof(c, args)
  File "/usr/local/lib/python2.7/site-packages/gemini-0.11.0a-py2.7.egg/gemini/tool_lof_sieve.py", line 55, in get_ind_lof
    transcript_pct = float(transcript_pos) / float(aa_length)
TypeError: float() argument must be a string or a number

**Comment by mmoisse** [comment]
I have the same problem and singled the problem down to splice_donor_variant's:
`CSQ=splice_donor_variant|||ENSG00000099866|MADCAM1|ENST00000587541||||-/163|protein_coding`
And it is caused by -/163 because changing this to 0/163, solves the problem

[chr19.VEP.3.part.vcf.zip](https://github.com/arq5x/gemini/files/174230/chr19.VEP.3.part.vcf.zip)




    $ gemini load --skip-gene-tables -v chr19.VEP.3.part.vcf --skip-gerp-bp --skip-cadd -t VEP test.3.db
    $ lof_sieve test.3.db 
    chrom   start   end     ref     alt     highest_impact  aa_change       var_trans_pos   trans_aa_length var_trans_pct   sample  genotype        gene    transcript      trans_type
    Traceback (most recent call last):
      File "/usr/local/bin/gemini", line 6, in <module>
        gemini.gemini_main.main()
      File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1179, in main
        args.func(parser, args)
      File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 728, in lof_sieve_fn
        tool_lof_sieve.lof_sieve(parser, args)
      File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/tool_lof_sieve.py", line 78, in lof_sieve
        get_ind_lof(c, args)
      File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/tool_lof_sieve.py", line 56, in get_ind_lof
        transcript_pct = float(transcript_pos) / float(aa_length.split("/")[1])
    TypeError: float() argument must be a string or a number
