### ISSUE TITLE
CyVcf dependency issue for v0.11.0 install using gemini_install.py --gemini-version 0.11.0

### ISSUE THREAD

**Issue by ddkinnamon** [arq5x/gemini#363]
I used the following command to install GEMINI 0.11.0 with a fixed dependency chain:

```
 python gemini_install.py --gemini-version 0.11.0 --nosudo ~/local/gemini/0.11.0 ~/local/gemini/0.11.0 /gemini_data

```

The install script completed successfully. However, when I tried to run master-test.sh, there were a number of the following errors relating to CyVcf:

```
Traceback (most recent call last):
  File "/nfs/06/osu7476/local/gemini/0.11.0/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/nfs/06/osu7476/local/gemini/0.11.0/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1105, in main
    args.func(parser, args)
  File "/nfs/06/osu7476/local/gemini/0.11.0/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 136, in load_fn
    gemini_load.load(parser, args)
  File "/nfs/06/osu7476/local/gemini/0.11.0/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 52, in load
    load_singlecore(args)
  File "/nfs/06/osu7476/local/gemini/0.11.0/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 60, in load_singlecore
    gemini_loader.populate_from_vcf()
  File "/nfs/06/osu7476/local/gemini/0.11.0/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 100, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/nfs/06/osu7476/local/gemini/0.11.0/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 406, in _prepare_variation
    gt_copy_numbers = np.array(var.gt_copy_numbers, np.float32)  # 1.0 2.0 2.1 -1
AttributeError: 'cyvcf.parser._Record' object has no attribute 'gt_copy_numbers'
```

After checking, I found that the installed version of CyVcf was 0.1.9.2 although the dependency in the root requirements.txt was updated to 0.1.10 in the commit tagged v0.11.0. It appears that the discrepancy arises because the dependency change was not also reflected in the gemini/versioning/0.11.0/requirements_pip.txt file that is used when the --gemini-version flag is provided to gemini_install.py. As an additional test, I used the syntax above to install v0.10.1 with a fixed dependency chain, and all unit tests completed successfully (other than the failure due to issue #332).

Thanks,
Dan

**Comment by chapmanb** [comment]
Dan;
Thanks so much for the report and taking the time to diagnose the issue. I pushed a fix which uses the correct version in 0.11.0 and should hopefully work now out of the box. Sorry about the issue and thanks again for all the help.

**Comment by ddkinnamon** [comment]
Thanks for posting the fix so quickly!

**Comment by arq5x** [comment]
Yes indeed, thanks Brad!
