### ISSUE TITLE
Problem loading VCF when include PED file

### ISSUE THREAD

**Issue by landyk01** [arq5x/gemini#370]
Hello,

I am having a problem loading a PED file into my gemini.db.  I am using the following command:

gemini load -v /path/to/annotated/snpeff/vcf -t snpEff -p /path/to/ped /path/to/gemini.db

I am getting the following output/error:

Traceback (most recent call last):
  File "/hpc/users/lindem03/packages/gemini/master/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/hpc/users/lindem03/packages/gemini/master/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1104, in main
    args.func(parser, args)
  File "/hpc/users/lindem03/packages/gemini/master/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 135, in load_fn
    gemini_load.load(parser, args)
  File "/hpc/users/lindem03/packages/gemini/master/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 52, in load
    load_singlecore(args)
  File "/hpc/users/lindem03/packages/gemini/master/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 57, in load_singlecore
    gemini_loader = GeminiLoader(args)
  File "/hpc/users/lindem03/packages/gemini/master/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 46, in __init__
    self._prepare_samples()
  File "/hpc/users/lindem03/packages/gemini/master/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 549, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/hpc/users/lindem03/packages/gemini/master/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 26, in load_ped_file
    ped_dict[fields[1]] = fields
IndexError: list index out of range

When I load just the VCF without the -p option it loads correctly. 

Help and suggestions would be greatly appreciated!
Thanks!

**Comment by arq5x** [comment]
Could you share the contents of your PED file? This will be tough to diagnose without it.

**Comment by landyk01** [comment]
Here is the PED file I am trying to load. 

#Family_ID      Individual_ID   Paternal_ID     Maternal_ID     Sex     Phenotype
1-00025 1-00025 1-00025-02      1-00025-01      -9      2
1-00025 1-00025-01      -9      -9      1       1
1-00025 1-00025-02      -9      -9      2       1

Thanks for your help!

**Comment by arq5x** [comment]
Unfortuantely, I can't replicate this with the current version.  Can you confirm you are using the current version, and if so, could you also send me the first 1000 lines of your VCF file?

**Comment by landyk01** [comment]
I am using version 0.11.0 - I believe that is the latest version.  

What is the best way to send you the vcf file?

Thanks!
