### ISSUE TITLE
Multiallelic VCF problem: ##FORMAT=<ID=AD,Number=R,... throwing an error

### ISSUE THREAD

**Issue by jdh237** [arq5x/gemini#405]
Here is the error message from one of the test commands --

$ gemini load --skip-gene-tables --test-mode --skip-gerp --skip-cadd -v test.multiple-alts.decomp.snpeff.vcf -t snpEff test.mad.db
Traceback (most recent call last):
  File "/software/gemini/tools/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 135, in load_fn
    gemini_load.load(parser, args)
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 52, in load
    load_singlecore(args)
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 57, in load_singlecore
    gemini_loader = GeminiLoader(args)
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 42, in __init__
    self.vcf_reader = self._get_vcf_reader()
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 194, in _get_vcf_reader
    return vcf.VCFReader(open(self.args.vcf), 'rb')
  File "parser.pyx", line 900, in cyvcf.parser.Reader.__init__ (cyvcf/parser.c:13465)
  File "parser.pyx", line 966, in cyvcf.parser.Reader._parse_metainfo (cyvcf/parser.c:14337)
  File "parser.pyx", line 101, in cyvcf.parser._vcf_metadata_parser.read_format (cyvcf/parser.c:3033)
SyntaxError: One of the FORMAT lines is malformed: ##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">

The problem appears to be with the cyvcf package. The parser.c file being distributed with that package is out of date. Downloading that project separately, generating a fresh parser.c file from the parser.pyx file, re-building the library, and copying the parser.so file to $DATA/anaconda/lib/python2.7/site-packages/cyvcf/ seems to fix the problem.

Just checked... an update was made to the cyvcf project related to this just an hour ago. Presumably this patch will make its way to the standard gemini install shortly. I'll post this Issue anyway in case anyone else is running into the same problem in the meantime.

-Jason

**Comment by arq5x** [comment]
Hi Jason,

Thanks for the heads up - @brentp caught this as well this morning and I have pushed a corrected .c file to cyvcf. We will try to get an update to GEMINI pushed out asap.

**Comment by delafont** [comment]
Hi,
I got this same error with 0.15 this morning. Is it supposed to be fixed ? I used "vt" for decomposing the multi-alternative variants, as the documentation suggests.

Traceback (most recent call last):
  File "/home/jdelafon/bin/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/scratch/fhgfs/jdelafon/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1117, in main
    args.func(parser, args)
  File "/scratch/fhgfs/jdelafon/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 278, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/scratch/fhgfs/jdelafon/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 723, in load
    gemini_loader = GeminiLoader(args)
  File "/scratch/fhgfs/jdelafon/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 63, in __init__
    self.vcf_reader = self._get_vcf_reader()
  File "/scratch/fhgfs/jdelafon/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 220, in _get_vcf_reader
    return vcf.VCFReader(sys.stdin, 'rb')
  File "cyvcf/parser.pyx", line 777, in cyvcf.parser.Reader.__init__ (cyvcf/parser.c:15685)
  File "cyvcf/parser.pyx", line 811, in cyvcf.parser.Reader._parse_metainfo (cyvcf/parser.c:16209)
  File "cyvcf/parser.pyx", line 75, in cyvcf.parser._vcf_metadata_parser.read_info (cyvcf/parser.c:2645)
SyntaxError: One of the INFO lines is malformed: ##INFO=\<ID=,Number=1,Type=String,Description="Original chr:pos:ref:alt encoding"\>

**Comment by brentp** [comment]
Hi @delafont , this is due to a bug in vt. I encountered the same thing and reported and it was promptly fixed: https://github.com/atks/vt/issues/30

if updating to the latest version of vt doesn't resolve this, let us know.

**Comment by delafont** [comment]
Thanks, that fixed it.
