### ISSUE TITLE
CalledProcessErrors in gemini load --scheduler lsf  caused by ' disk I/O error'  and 'database is locked' errors

### ISSUE THREAD

**Issue by bw2** [arq5x/gemini#427]
`gemini load --cores 5 ` works great when I run it in an interactive shell on a cluster node, but I'm having trouble getting it to work with `--scheduler lsf`, distributed over multiple nodes .  

My command line is:

```
gemini load -t VEP -v 1kg.vep.vcf.gz -p ../sample_data/1kg.ped 1kg.vep.gemini.db --cores 200 --scheduler lsf --queue h
```

which eventually fails every time due to CalledProcessError on a large subset of (but not all) the chunks:
```
Loading 110297 variants.
Breaking 1kg.vep.vcf.gz into 200 chunks.
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "/humgen/atgu1/fs03/weisburd/gemini_install/bin/gemini", line 4, in <module>
    __import__('pkg_resources').run_script('gemini==0.12.2', 'gemini')
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/pkg_resources/__init__.py", line 698, in run_script
    
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/pkg_resources/__init__.py", line 1616, in run_script
    
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/EGG-INFO/scripts/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_main.py", line 1143, in main
    args.func(parser, args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_main.py", line 137, in load_fn
    gemini_load.load(parser, args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_load.py", line 51, in load
    load_ipython(args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_load.py", line 85, in load_ipython
    chunks = load_chunks_ipython(grabix_file, args, view)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_load.py", line 289, in load_chunks_ipython
    chunk_dbs = view.map(load_chunk, chunk_steps, [load_args] * total_chunks)
  File "<string>", line 2, in map
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 55, in sync_results
    ret = f(self, *args, **kwargs)
  File "<string>", line 2, in map
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 40, in save_ids
    ret = f(self, *args, **kwargs)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 1123, in map
    return pf.map(*sequences)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/IPython/parallel/client/remotefunction.py", line 271, in map
    ret = self(*sequences)
  File "<string>", line 2, in __call__
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/IPython/parallel/client/remotefunction.py", line 78, in sync_view_results
    return f(self, *args, **kwargs)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/IPython/parallel/client/remotefunction.py", line 254, in __call__
    return r.get()
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/IPython/parallel/client/asyncresult.py", line 104, in get
    raise self._exception
IPython.parallel.error.CompositeError: one or more exceptions from call to method: load_chunk
[57:apply]: CalledProcessError: Command 'grabix grab 1kg.vep.vcf.gz 1 551 | gemini load_chunk -v - -t VEP -p ../sample_data/1kg.ped          -o 1 1kg.vep.vcf.chunk0.db' returned non-zero exit status 1
[51:apply]: CalledProcessError: Command 'grabix grab 1kg.vep.vcf.gz 552 1102 | gemini load_chunk -v - -t VEP -p ../sample_data/1kg.ped          -o 552 1kg.vep.vcf.chunk1.db' returned non-zero exit status 1
[28:apply]: CalledProcessError: Command 'grabix grab 1kg.vep.vcf.gz 1103 1653 | gemini load_chunk -v - -t VEP -p ../sample_data/1kg.ped          -o 1103 1kg.vep.vcf.chunk2.db' returned non-zero exit status 1
[38:apply]: CalledProcessError: Command 'grabix grab 1kg.vep.vcf.gz 1654 2204 | gemini load_chunk -v - -t VEP -p ../sample_data/1kg.ped          -o 1654 1kg.vep.vcf.chunk3.db' returned non-zero exit status 1
.... 93 more exceptions ...
```

To trouble shoot this, I added log files for the chunk subprocesses: 
```
diff --git a/gemini/gemini_load.py b/gemini/gemini_load.py
index 56270ff..ec692fb 100755
--- a/gemini/gemini_load.py
+++ b/gemini/gemini_load.py
@@ -293,7 +293,11 @@ def load_chunk(chunk_step, kwargs):
     start, stop = chunk
     args = combine_dicts(locals(), kwargs)
     gemini_load = gemini_pipe_load_cmd().format(**args)
-    subprocess.check_call(gemini_load, shell=True)
+    with open("load_chunk_%d.log" % chunk_num, "w") as log_file:
+        log_file.write(gemini_load + "\n")
+        subprocess.check_call(gemini_load, shell=True, stdout=log_file, stderr=log_file)
+        log_file.write("done - " + gemini_load + "\n")
+        #os.remove(log_file.name)
     chunk_db = args["vcf"] + ".chunk" + str(chunk_num) + ".db"
     return chunk_db
```

Then, when I looked at the log files, it turned out that 95 out 200 chunks failed due to:

```
Traceback (most recent call last):
  File "/humgen/atgu1/fs03/weisburd/gemini_install/bin/gemini", line 4, in <module>
    __import__('pkg_resources').run_script('gemini==0.12.2', 'gemini')
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/pkg_resources/__init__.py", line 698, in run_script
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/pkg_resources/__init__.py", line 1616, in run_script
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/EGG-INFO/scripts/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_main.py", line 1143, in main
    args.func(parser, args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_main.py", line 227, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_load_chunk.py", line 693, in load
    gemini_loader = GeminiLoader(args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_load_chunk.py", line 40, in __init__
    self._create_db()
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_load_chunk.py", line 264, in _create_db
    self.c.execute('PRAGMA synchronous = OFF')
sqlite3.OperationalError: database is locked
```

and another  2 out of 200 failed with:

```
Traceback (most recent call last):
  File "/humgen/atgu1/fs03/weisburd/gemini_install/bin/gemini", line 4, in <module>
    __import__('pkg_resources').run_script('gemini==0.12.2', 'gemini')
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/pkg_resources/__init__.py", line 698, in run_script
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/pkg_resources/__init__.py", line 1616, in run_script
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/EGG-INFO/scripts/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_main.py", line 1143, in main
    args.func(parser, args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_main.py", line 227, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_load_chunk.py", line 698, in load
    gemini_loader.update_gene_table()
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gemini_load_chunk.py", line 640, in update_gene_table
    gene_table.update_cosmic_census_genes(self.c, self.args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/gene_table.py", line 72, in update_cosmic_census_genes
    database.update_gene_summary_w_cancer_census(cursor, cosmic_census_genes)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini-0.12.2-py2.7.egg/gemini/database.py", line 463, in update_gene_summary_w_cancer_census
    cursor.executemany(update_qry, genes)
sqlite3.OperationalError: disk I/O error
```

When I googled this, the most plausible explanation was that this was an incompatibility between SQLite and NFS which manifests itself as these types of errors. 
(https://www.sqlite.org/faq.html#q5
http://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible
http://sqlite.1065341.n5.nabble.com/sqlite3-OperationalError-disk-I-O-error-td18568.html)

Has anybody else seen these errors before?

Thanks
-Ben

**Comment by arq5x** [comment]
Thanks for reporting this issue.  There is a stated issue about locking bugs in NFS (https://www.sqlite.org/howtocorrupt.html), but it is still odd to me because each process creates a distinct database to avoid collisions. Therefore, in theory this issue shouldn't arise on NFS. I wonder if somehow filenames are being reused on the same nodes thereby causing this issue? We will have to spend some time looking into this.

**Comment by bw2** [comment]
@arq5x Thanks for the quick response. I'm surprised SQLite doesn't have some built-in approach to deal with this. 
To try to further debug this, I modified the PRAGMAs to:
```
self.c.execute('PRAGMA locking_mode = EXCLUSIVE')
# self.c.execute('PRAGMA synchronous = OFF')                                                                                                                                         
self.c.execute('PRAGMA journal_mode=MEMORY')
```
but still got the same number of `database locked` errors.

Perhaps this could be handled with a command-line option that lets users specify a non-NFS dir (eg.  /local/scratch) for db operations?

**Comment by brentp** [comment]
so, this occurs when using the ipython scheduler and not when using multiple local cores?

**Comment by arq5x** [comment]
@chapmanb or @roryk - have you noticed anything like this on your end? Or perhaps you are not using NFS?

**Comment by roryk** [comment]
Hi everyone, sorry about the problems. I haven't noticed this and we are using NFS in places but that doesn't mean it isn't the issue, we've definitely run into SQLite not playing well with NFS in other places. Ben, one thing you could do to work around this would be to ask for all of the cores on one machine and just run it using the multiple local cores. I'm not too sure how to deal with the underlying issue though, if that is what it is.

**Comment by bw2** [comment]
@brentp yes.. @roryk your suggestion does work - although I'm a little surprised as I don't see a difference from the --scheduler LSF approach from SQLite's point of view. I'd like to give this one more try before I give up on LSF since it's seems like an incredibly powerful feature. 
I'll see if I can hack the load and merge code to create the db in /local/scrach and then move it to where it's supposed to be on NFS after the cursor is closed. Let me know if you see any problems with this test, or if there are better ways to troubleshoot this.

**Comment by bw2** [comment]
Moving the dbs to/from local disk did fix it, and I can now load the db at 200+ variants / second!
Would you by chance be interested in adding this type of loading as an option? If yes, I could put in a pull request...

My the changes are in 2 places in `gemini/gemini_load.py`:
```
 def load_chunk(chunk_step, kwargs):
     chunk_num, chunk = chunk_step
     start, stop = chunk
     args = combine_dicts(locals(), kwargs)
+    tmp_db = get_temp_dbs(1, tempfile.gettempdir())[0]
+    args["chunk_db_filename"] = tmp_db
     gemini_load = gemini_pipe_load_cmd().format(**args)
     subprocess.check_call(gemini_load, shell=True)
     chunk_db = args["vcf"] + ".chunk" + str(chunk_num) + ".db"
+    shutil.move(tmp_db, chunk_db)
     return chunk_db
```
and
```
 def merge_chunks(chunks, db):
-    cmd = get_merge_chunks_cmd(chunks, db)
+    # move chunks to temp dir
+    tmp_chunks = get_temp_dbs(len(chunks), tempfile.gettempdir())
+    tmp_db = get_temp_dbs(1, tempfile.gettempdir())[0]
+    for chunk, tmp_chunk in zip(chunks, tmp_chunks):
+        shutil.move(chunk, tmp_chunk)
+    cmd = get_merge_chunks_cmd(tmp_chunks, tmp_db)
     print "Merging chunks."
     subprocess.check_call(cmd, shell=True)
-    cleanup_temp_db_files(chunks)
+    cleanup_temp_db_files(tmp_chunks)
+    shutil.move(tmp_db, db)
     return db
```

and I also had to add another PRAGMA:  `PRAGMA temp_store = 2`
to prevent 'Disk is full' errors (which occurred intermittently even though there was plenty of disk space).

**Comment by brentp** [comment]
@bw2, this is more @roryk and @chapmanb 's area, but I think this would be great! Maybe we could only do this when a scheduler is specified? Can you open a PR?

Either way, once the next release is out (we have a lot of pending changes), I think it'd be great to incorporate this.

**Comment by bw2** [comment]
@brentp Great! After thinking about it one more time, perhaps the right way to implement this is to first try the load or merge using the current method, and then if a sqlite3.OperationalError occurs, retry with moving to/from temp (since I'm only seeing these errors on << 50% of the loads / merges). 

I'll put it in a PR and we can iterate.

**Comment by arq5x** [comment]
Thanks so much for digging into this. In my mind, it seems like we should supply an option for the user to supply a "temp" path for the intermediate files and we should have the help explicitly mention the utility of this path when using NFS with the --queue option. We would be very happy to bring in a PR if you are willing to do it. Thanks!

**Comment by arq5x** [comment]
Once @brentp finishes tests on our end, we can close this, no?

**Comment by bw2** [comment]
That sounds good to me.
