### ISSUE TITLE
"IndexError: list index out of range" error with gemini load

### ISSUE THREAD

**Issue by jdownie2389** [arq5x/gemini#431]
I'm running into a list index out of range error when I try to load a VEP annotated vcf file (with dbNSFP information). I've tried this with a vcf file that I have successfully loaded in the past. I'm running this with Gemini v0.12.2. Below is the command and error that I'm getting.

Command
```
nohup gemini load -v sals_samples_intervals_SNP_INDEL_recal_euro.recode.VEP_75.vcf -t VEP --core 10 sals_samples_intervals_SNP_INDEL_recal_euro.recode.VEP_75.db &
```

log output
```
CADD scores are not being loaded because the annotation file could not be found.
`Run gemini update --dataonly --extra cadd_score` to install the annotation file.


GERP per bp is not being loaded because the annotation file could not be found.
    Run `gemini update --dataonly --extra gerp_bp` to install the annotation file.

Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range

warning: variant with multiple alternate alleles found.
         in order to reduce the number of false negatives
         we recommend to split multiple alts. see:                 http://gemini.readthedocs.org/en/
latest/content/preprocessing.html#preprocess
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk
.py", line 110, in populate_from_vcf
    for var in self.vcf_reader:
  File "parser.pyx", line 1041, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:18668)
  File "parser.pyx", line 1089, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19370)
  File "parser.pyx", line 853, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16228)
IndexError: list index out of range
Loading with existing bgzip (sals_samples_intervals_SNP_INDEL_recal_euro.recode.VEP_75.vcf.gz) versi
on of sals_samples_intervals_SNP_INDEL_recal_euro.recode.VEP_75.vcf.
Loading 288307 variants.
Breaking sals_samples_intervals_SNP_INDEL_recal_euro.recode.VEP_75.vcf.gz into 10 chunks.
Loading chunk 0.
Loading chunk 1.
Loading chunk 2.
Loading chunk 3.
Loading chunk 4.
Loading chunk 5.
Loading chunk 6.
Loading chunk 7.
Loading chunk 8.
Loading chunk 9.
Done loading 288307 variants in 10 chunks.
2015-04-06 14:15:29 merging 10 chunks.
2015-04-06 14:15:32 merging 5 chunks.
2015-04-06 14:15:34 merging 2 chunks.
2015-04-06 14:15:36 indexing final database.
Traceback (most recent call last):
  File "/kbod/jdownie/opt/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 1141, in main
    args.func(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",
line 135, in load_fn
    gemini_load.load(parser, args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py",
line 50, in load
    load_multicore(args)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py",
line 77, in load_multicore
    gemini_annotate.add_extras(args.db, chunks)
  File "/kbod/jdownie/opt/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_annotate.p
y", line 364, in add_extras
    assert os.path.exists(header_file)
AssertionError
```
-Jon

**Comment by brentp** [comment]
Jon, thanks for reporting. We have fixed this in cyvcf and will be making a new release soon.

**Comment by andreyurch** [comment]
Dear Colleagues!   I just got an error (I have the latest version of GEMINI):

Traceback (most recent call last):
  File "/ifs/apps/yurchenko/GEMINI/tooldir/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
    args.func(parser, args)
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 298, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 800, in load
    gemini_loader.populate_from_vcf()
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 203, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 492, in _prepare_variation
    gt_bases = var.gt_bases
  File "cyvcf2/cyvcf2.pyx", line 725, in cyvcf2.cyvcf2.Variant.gt_bases.__get__ (cyvcf2/cyvcf2.c:19337)
IndexError: list index out of range

There is no the error when I use only first 1000 variants from my vcf file

Thank you very much!

**Comment by brentp** [comment]
can you update cyvcf2: 
```
conda update -c bioconda cyvcf2
```
this should get you version 0.4 which has a fix for an issue that looks like it might be the same as you are seeing.

**Comment by andreyurch** [comment]
I have updated it but got the same error:


$ conda update -c bioconda cyvcf2
Fetching package metadata .........
# All requested packages already installed.
# packages in environment at /ifs/apps/yurchenko/GEMINI/datadir/anaconda:
#
cyvcf2                    0.4.0                    py27_0    bioconda

$ gemini load -v TRIO_MERGED.vcf test.db                   
CADD scores are being loaded (to skip use:--skip-cadd).
GERP per bp is being loaded (to skip use:--skip-gerp-bp).

warning: variant with multiple alternate alleles found.
         in order to reduce the number of false negatives
         we recommend to split multiple alts. see:                 http://gemini.readthedocs.org/en/latest/content/preprocessing.html#preprocess
Traceback (most recent call last):
  File "/ifs/apps/yurchenko/GEMINI/tooldir/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
    args.func(parser, args)
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
    gemini_load.load(parser, args)
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
    load_singlecore(args)
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 60, in load_singlecore
    gemini_loader.populate_from_vcf()
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 203, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
  File "/ifs/apps/yurchenko/GEMINI/datadir/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 492, in _prepare_variation
    gt_bases = var.gt_bases
  File "cyvcf2/cyvcf2.pyx", line 725, in cyvcf2.cyvcf2.Variant.gt_bases.__get__ (cyvcf2/cyvcf2.c:19337)
IndexError: list index out of range

**Comment by brentp** [comment]
can you sent a small portion of the VCF that shows the error?

**Comment by andreyurch** [comment]
Please find attached it, but if I use only first 1000 lines from this vcf it works without any problem. 
[test.vcf.zip](https://github.com/arq5x/gemini/files/331891/test.vcf.zip)

**Comment by brentp** [comment]
you sent me the first 1K lines, but you don't see the bug in the first 1K lines?

can you send me part of the VCF that creates the bug?

you should be able to use the code below to get the chrom and POS of the lines that are causing problems?
```
from cyvcf2 import VCF

for v in VCF('test.vcf'):
    try:
         v.gt_bases
    except:
        print v.CHROM, v.start + 1
 
```

and let me know if it has an error? I'm not seeing one.

**Comment by andreyurch** [comment]
Please find attached the whole sample of bad lines from my vcf


[bad_lines.vcf.zip](https://github.com/arq5x/gemini/files/332034/bad_lines.vcf.zip)

**Comment by brentp** [comment]
Thanks for the test case!
I see. you have haploid calls on X for some of these. We're expecting diploid calls in gemini. I'll see if I can fix the bug in cyvcf2, but gemini won't behave as expected for X-linked stuff when you use haploid calls on X

**Comment by andreyurch** [comment]
Thank you! you are right.  And not only on X, I think it is caused by too sophisticated variant calling.
