### ISSUE TITLE
Installation failure in install_testbase

### ISSUE THREAD

**Issue by rchekaluk** [arq5x/gemini#438]
The following error occurs on a simple [install](http://gemini.readthedocs.org/en/latest/content/installation.html) (Ubuntu trusty 14.04.2 LTS). Commit https://github.com/arq5x/gemini/commit/e3e7c8a4740ecf1976ecceaae920b98dec1e9a67 looks suspicious:
```
$ cd /tmp
$ wget https://raw.github.com/arq5x/gemini/master/gemini/scripts/gemini_install.py
$ sudo python gemini_install.py /usr/local /usr/local/share/gemini
...
* downloading https://s3.amazonaws.com/gemini-annotations/cancer_gene_census.20140120.tsv to /usr/local/share/gemini/data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 65442  100 65442    0     0   105k      0 --:--:-- --:--:-- --:--:--  105k
* downloading https://s3.amazonaws.com/gemini-annotations/ExAC.r0.3.sites.vep.tidy.vcf.gz to /usr/local/share/gemini/data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3148M  100 3148M    0     0  8203k      0  0:06:33  0:06:33 --:--:-- 8191k
* downloading https://s3.amazonaws.com/gemini-annotations/ExAC.r0.3.sites.vep.tidy.vcf.gz.tbi to /usr/local/share/gemini/data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  853k  100  853k    0     0  4600k      0 --:--:-- --:--:-- --:--:-- 4612k
['data', 'anaconda', 'gemini-config.yaml']
Cloning into 'gemini'...
remote: Counting objects: 7469, done.
remote: Total 7469 (delta 0), reused 0 (delta 0), pack-reused 7469
Receiving objects: 100% (7469/7469), 52.17 MiB | 8.10 MiB/s, done.
Resolving deltas: 100% (5066/5066), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "gemini_install.py", line 410, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 102, in main
    test_script = install_testbase(args.datadir, remotes["gemini"], gemini)
  File "gemini_install.py", line 282, in install_testbase
    for f in os.listdir(os.path.join(cur_dir, "gtmp", "data")):
OSError: [Errno 2] No such file or directory: '/tmp/tmpgemini_install/gtmp/data'
```

**Comment by arq5x** [comment]
Hmm. Thanks for reporting - I will try to reproduce

**Comment by brentp** [comment]
Looking into it. I mostly test using --nosudo (and I just double-checked that worked) so it must be something related to that.
