### ISSUE TITLE
Master-test.sh Errors in Window.t* tests using bedtools

### ISSUE THREAD

**Issue by nfarzaneh** [arq5x/gemini#451]
Hello,

I get errors for all the window.t* tests when I run the master-test.sh.

GEMINI VERSION: 0.14.0
OS: LINUX
BEDTOOLS: v2.22.1

Let me know if you need any other information.

Thanks a lot,
Nima

===============================

ERROR MESSAGE:

> 0a1,2
> \>chr1	30000	40000	1.0
> \>chr1	60000	70000	1.0
fail
    window.t05...\c
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1076, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 602, in windower_fn
    gemini_windower.windower(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_windower.py", line 87, in windower
    make_windows(c, args, temp_file)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_windower.py", line 65, in make_windows
    windowed_analysis = windows.map(window_data, o=args.op_type, c=op_col)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 668, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 243, in wrapped
    check_stderr=check_stderr)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/pybedtools/helpers.py", line 440, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

>bedtools map -o collapse -c 4 -b .temp.54653 -a /tmp/pybedtools.tYwNDS.tmp

>Error message was:

>*****
>***** ERROR: Requested column 4, but database file /tmp/pybedtools.tYwNDS.tmp only has fields 1 - 3.

>Tool:    bedtools map (aka mapBed)
>Version: v2.22.1
>Summary: Apply a function to a column from B intervals that overlap A.
>[...]

**Comment by arq5x** [comment]
Unless you are using the window tool, you can safely ignore these test failures. We need to adjust the GEMINI code to be in sync with changes to the window tool in BEDTOOLS.
