### ISSUE TITLE
load failure -  TypeError: 'int' object is not iterable in cyvcf.parser._Call.gt_phred_likelihoods

### ISSUE THREAD

**Issue by mjsduncan** [arq5x/gemini#471]
this may or may not be related to issue https://github.com/arq5x/gemini/issues/456 i submitted earlier.  after many hours of loading a VEP annotated vcf file with command:

>gemini load --cores 8 -t VEP -v sc17VEP.vcf --tempdir . sc17VEP.db

2 threads failed with:

>  File "cyvcf/parser.pyx", line 271, in cyvcf.parser._Call.gt_phred_likelihoods.__get__ (cyvcf/parser.c:5517)
>TypeError: 'int' object is not iterable

and then when the other threads finished, the chunk merge failed with:

>ValueError: Processing failed on GEMINI chunk load

so my questions are
1. is the error in `gt_phred_likelihoods` due to missing values in the `--extra cadd_score` file, and if so
2. is there any way to salvage the failed chunks if the cadd file is fixed?

below are the gory details from the trace back, before and after `top` output, and the chunk file info.  thanks to the gemini team for all your great work!

(the #x are my additions to keep track of the chunk threads, not links to other issues)

#### `top - 09:47:47`
31431 biocog    20   0  673804 363588   5120 R 100.0  2.2 300:10.80 gemini  #0
31434 biocog    20   0  673068 364236   5232 R 100.0  2.2 299:03.05 gemini  #1
31437 biocog    20   0  678956 369312   5016 R 100.0  2.3 299:15.74 gemini  #2
31440 biocog    20   0  677164 367028   5120 R 100.0  2.2 299:49.39 gemini  #3
31443 biocog    20   0  665356 356896   5300 R 100.0  2.2 299:56.87 gemini  #4
31449 biocog    20   0  680716 370764   5000 R 100.0  2.3 298:50.31 gemini  #6
31446 biocog    20   0  699152 390236   5144 R  99.7  2.4 300:22.72 gemini  #5
31452 biocog    20   0  683564 373852   5300 R  94.7  2.3 299:16.23 gemini  #7

#### `gemini` output

pid 31452: 1109999 variants processed.  #7
pid 31443: 1069999 variants processed.  #4
pid 31437: 1139999 variants processed.  #2
pid 31434: 1099999 variants processed.  #1
pid 31449: 1089999 variants processed.  #6
pid 31440: 1129999 variants processed.  #3
pid 31446: 1079999 variants processed.  #5
pid 31431: 1079999 variants processed.  #0
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1117, in main
    args.func(parser, args)
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 278, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 727, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 133, in populate_from_vcf
    for var in self.vcf_reader:
  File "cyvcf/parser.pyx", line 1063, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:19916)
  File "cyvcf/parser.pyx", line 1126, in cyvcf.parser.Reader.parse (cyvcf/parser.c:20878)
  File "cyvcf/parser.pyx", line 974, in cyvcf.parser.Reader._parse_samples (cyvcf/parser.c:18613)
  File "cyvcf/parser.pyx", line 271, in cyvcf.parser._Call.gt_phred_likelihoods.__get__ (cyvcf/parser.c:5517)
TypeError: 'int' object is not iterable
pid 31452: 1119999 variants processed.  #7
pid 31443: 1079999 variants processed.  #4
pid 31437: 1149999 variants processed.  #2
pid 31446: 1089999 variants processed.  #5
pid 31440: 1139999 variants processed.  #3
pid 31434: 1109999 variants processed.  #1
pid 31431: 1089999 variants processed.  #0
pid 31443: 1089999 variants processed.  #4

...

pid 31440: 1309999 variants processed.  #3
pid 31446: 1269999 variants processed.  #5
pid 31452: 1329999 variants processed.  #7
pid 31443: 1269999 variants processed.  #4
pid 31431: 1269999 variants processed.  #0
pid 31452: 1339999 variants processed.  #7
pid 31434: 1299999 variants processed.  #1
pid 31437: 1329999 variants processed.  #2
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1117, in main
    args.func(parser, args)
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 278, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 727, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 133, in populate_from_vcf
    for var in self.vcf_reader:
  File "cyvcf/parser.pyx", line 1063, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:19916)
  File "cyvcf/parser.pyx", line 1126, in cyvcf.parser.Reader.parse (cyvcf/parser.c:20878)
  File "cyvcf/parser.pyx", line 974, in cyvcf.parser.Reader._parse_samples (cyvcf/parser.c:18613)
  File "cyvcf/parser.pyx", line 271, in cyvcf.parser._Call.gt_phred_likelihoods.__get__ (cyvcf/parser.c:5517)
TypeError: 'int' object is not iterable
pid 31446: 1279999 variants processed.  #5
pid 31443: 1279999 variants processed.  #4
pid 31452: 1349999 variants processed.  #7
pid 31440: 1319999 variants processed.  #3
pid 31434: 1309999 variants processed.  #1
pid 31437: 1339999 variants processed.  #2
pid 31452: 1359999 variants processed.  #7

#### `top - 17:28:55`
31443 biocog    20   0  674828 344960   4436 R 100.0  2.1 756:56.15 gemini  #4
31446 biocog    20   0  663312 288864   4352 R 100.0  1.8 755:58.05 gemini  #5
31434 biocog    20   0  673324 342504   4340 R 100.0  2.1 756:26.76 gemini  #1
31437 biocog    20   0  681772 346792   4256 R 100.0  2.1 756:38.00 gemini  #2
31440 biocog    20   0  670764 336952   4272 R  99.7  2.1 756:50.80 gemini  #3
31452 biocog    20   0  671532 274456   4436 R  99.7  1.7 756:53.93 gemini  #7

#### `gemini` output
...
pid 31443: 1756450 variants processed.  #4
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1117, in main
    args.func(parser, args)
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 183, in load_fn
    gemini_load.load(parser, args)
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 50, in load
    load_multicore(args)
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 80, in load_multicore
    chunks = load_chunks_multicore(grabix_file, args)
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 247, in load_chunks_multicore
    wait_until_finished(procs)
  File "/home/biocog/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 338, in wait_until_finished
    raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load
[2]+  Terminated              gemini load --cores 8 -t VEP -v sc17VEP.vcf --tempdir . sc17VEP.db

#### `ll | grep chunk`
-rw-r--r--  1 biocog biocog  3608771584 May 21 16:10 sc17VEP.vcf.chunk0.db  #failed thread chunk
-rw-r--r--  1 biocog biocog  4934328320 May 21 18:59 sc17VEP.vcf.chunk1.db
-rw-r--r--  1 biocog biocog  4801579008 May 21 19:04 sc17VEP.vcf.chunk2.db
-rw-r--r--  1 biocog biocog  4816466944 May 21 19:08 sc17VEP.vcf.chunk3.db
-rw-r--r--  1 biocog biocog  4839892992 May 21 19:20 sc17VEP.vcf.chunk4.db
-rw-r--r--  1 biocog biocog  4888034304 May 21 19:06 sc17VEP.vcf.chunk5.db
-rw-r--r--  1 biocog biocog  3275911168 May 21 14:40 sc17VEP.vcf.chunk6.db  #failed thread chunk
-rw-r--r--  1 biocog biocog  4916117504 May 21 18:13 sc17VEP.vcf.chunk7.db

**Comment by brentp** [comment]
I just pushed a fix for this to cyvcf, to be more defensive, but it sounds like you are getting some genotype likelihoods as ints. Can you show the result of:

```
grep ^# $VCF | grep GL
```
and what did you use to call variants?

**Comment by mjsduncan** [comment]
`grep ^# $VCF | grep GL`
`##FORMAT=<ID=GL,Number=.,Type=Integer,Description="Genotype Likelihood">`

so it looks like they're being defined as ints but only 2 of 8 chunks is failing?

the variants were called using complete gonmic's CGI pipeline 2.0.2. i received the data as tab files for each sample, converted them to vcf with cgatools and merged them together with vcftools.

as an aside, using this line to fix the AD tag:  
>sed 's/ID=AD,Number=./ID=AD,Number=R/'

didn't work so i dropped the whole column using `bcftools annotate -x`

thanks for the quick follow up!

**Comment by brentp** [comment]
ok. we haven't tested on any CG vcfs, so this isn't too surprising. If you can send a small subset, I'll see if I can get it working. That header line should be:
```
 ##FORMAT=<ID=GL,Number=G,Type=Integer,Description="Genotype Likelihood">
```
you could see if making that change gets you any further.

What is the original FORMAT header for ID=AD?

**Comment by mjsduncan** [comment]
hi brent, as is probably obvious, i'm kind of a noob .  how do i get your
push?  will gemini update --devel work?  thx again

**Comment by brentp** [comment]
no. it's only a change to cyvcf, so, you could do (from your gemini env):

```
git clone https://github.com/brentp/cyvcf && cd cyvcf
python setup.py install
```

**Comment by mjsduncan** [comment]
the AD header line is
`##FORMAT=<ID=AD,Number=2,Type=Integer,Description="Allelic depths (number
of reads in each observed allele)">`

after the sed substitution it failed right away tho i can't remember
exactly how.  the data set is proprietary, can i send you a subset
privately?

**Comment by brentp** [comment]
yes, please do (bpederse / gmail) . It seems like there's enough wrong that it might be a challenge, but we'll see.

**Comment by mjsduncan** [comment]
thanks to brent for pushing a fix that compensates for idiosyncracies in the vcf format output by complete genomics cgatools!
