### ISSUE TITLE
VCF output is broken

### ISSUE THREAD

**Issue by jgoecks** [arq5x/gemini#488]
When producing VCF, the INFO field appears to be binary encoded. This seems to be the case for an GEMINI database. I will try to debug when I have time, but that may be a bit down the road.

**Comment by arq5x** [comment]
Thansk for reporting this, Jeremy!  Looks like it needs to be unpacked:

https://github.com/arq5x/gemini/blob/master/gemini/GeminiQuery.py#L305

should be more like:
https://github.com/arq5x/gemini/blob/master/gemini/GeminiQuery.py#L429

**Comment by brentp** [comment]
should be able to just use row['info'] on line 305. I'll have a look.

**Comment by arq5x** [comment]
ah right, as it should be calling the getter and doing the right thing.

**Comment by nswh** [comment]
```
# gemini query -q "select chrom,start,end from variants limit 3" NA12878.db             
chr1	601435	601436
chr1	601666	601667
chr1	607859	607860
# gemini query -q "select chrom,start,end from variants limit 3" NA12878.db --format json
{"start": 601435, "end": 601436, "chrom": "chr1"}
{"start": 601666, "end": 601667, "chrom": "chr1"}
{"start": 607859, "end": 607860, "chrom": "chr1"}
# gemini query -q "select chrom,start,end from variants limit 3" NA12878.db --format vcf 
SQL error: (sqlite3.OperationalError) no such column: info
[SQL: select chrom, start, end, vcf_id, ref, alt, qual, filter, info,gts,gt_types,gt_phases,gt_depths,gt_ref_depths,gt_alt_depths,gt_quals,gt_alt_freqs from variants limit 3]
(Background on this error at: http://sqlalche.me/e/e3q8)

SQL error: (sqlite3.OperationalError) no such column: info
[SQL: select chrom, start, end, vcf_id, ref, alt, qual, filter, info,gts,gt_types,gt_phases,gt_depths,gt_ref_depths,gt_alt_depths,gt_quals,gt_alt_freqs from variants limit 3]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/opt/gemini/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/opt/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
    args.func(parser, args)
  File "/opt/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 439, in query_fn
    gemini_query.query(parser, args)
  File "/opt/data/anaconda/lib/python2.7/site-packages/gemini/gemini_query.py", line 169, in query
    run_query(args)
  File "/opt/data/anaconda/lib/python2.7/site-packages/gemini/gemini_query.py", line 135, in run_query
    gene_needed, args.show_families, subjects=subjects)
  File "/opt/data/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 653, in run
    self.result_proxy = res = iter(self._apply_query())
  File "/opt/data/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 907, in _apply_query
    res = self._execute_query()
  File "/opt/data/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 884, in _execute_query
    raise ValueError("The query issued (%s) has a syntax error." % self.query)
ValueError: The query issued (select chrom, start, end, vcf_id, ref, alt, qual, filter, info,gts,gt_types,gt_phases,gt_depths,gt_ref_depths,gt_alt_depths,gt_quals,gt_alt_freqs from variants limit 3) has a syntax error.
```

**Comment by nswh** [comment]
Not sure whether this issue has been fixed or not. With the latest vcf2db.py, seems there is no info column in the final db. 
`# gemini -v
gemini 0.30.2`
