### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by simplelive** [arq5x/gemini#511]
# gemini load --cores 8 -v my.snp.vcf -t snpEff my.db
CADD scores are being loaded (to skip use:--skip-cadd).
GERP per bp is being loaded (to skip use:--skip-gerp-bp).
Loading with existing bgzip (my.snp.vcf.gz) version of my.snp.vcf.
Loading 15414 variants.
Breaking my.snp.vcf.gz into 8 chunks.
Loading chunk 0.
Loading chunk 1.
Loading chunk 2.
Loading chunk 3.
Loading chunk 4.
Loading chunk 5.
Loading chunk 6.
Loading chunk 7.
Traceback (most recent call last):
  File "/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 292, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 757, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 140, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 313, in _prepare_variation
    call_rate = var.call_rate
  File "cyvcf/parser.pyx", line 506, in cyvcf.parser._Record.call_rate (cyvcf/parser.c:10278)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 292, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 757, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 140, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 313, in _prepare_variation
    call_rate = var.call_rate
  File "cyvcf/parser.pyx", line 506, in cyvcf.parser._Record.call_rate (cyvcf/parser.c:10278)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 292, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 757, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 140, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 313, in _prepare_variation
    call_rate = var.call_rate
  File "cyvcf/parser.pyx", line 506, in cyvcf.parser._Record.call_rate (cyvcf/parser.c:10278)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 292, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 757, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 140, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 313, in _prepare_variation
    call_rate = var.call_rate
  File "cyvcf/parser.pyx", line 506, in cyvcf.parser._Record.call_rate (cyvcf/parser.c:10278)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 292, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 757, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 140, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 313, in _prepare_variation
    call_rate = var.call_rate
  File "cyvcf/parser.pyx", line 506, in cyvcf.parser._Record.call_rate (cyvcf/parser.c:10278)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 292, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 757, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 140, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 313, in _prepare_variation
    call_rate = var.call_rate
  File "cyvcf/parser.pyx", line 506, in cyvcf.parser._Record.call_rate (cyvcf/parser.c:10278)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 292, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 757, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 140, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 313, in _prepare_variation
    call_rate = var.call_rate
  File "cyvcf/parser.pyx", line 506, in cyvcf.parser._Record.call_rate (cyvcf/parser.c:10278)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 292, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 757, in load
    extra_fields = gemini_loader.populate_from_vcf()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 140, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 313, in _prepare_variation
    call_rate = var.call_rate
  File "cyvcf/parser.pyx", line 506, in cyvcf.parser._Record.call_rate (cyvcf/parser.c:10278)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 197, in load_fn
    gemini_load.load(parser, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 50, in load
    load_multicore(args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 80, in load_multicore
    chunks = load_chunks_multicore(grabix_file, args)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 249, in load_chunks_multicore
    wait_until_finished(procs)
  File "/gemini/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 340, in wait_until_finished
    raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load

=========================================================================

# uname -a
Linux CentOS1 2.6.32-504.30.3.el6.x86_64 #1 SMP Wed Jul 15 10:13:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

#
# gemini -v
gemini 0.16.2

# snpEff -version
4.1g

# more my.snp.vcf
##SnpEffVersion="4.1g (build 2015-05-17), by Pablo Cingolani"
##SnpEffCmd="SnpEff  GRCh37.70 my.vcf "
##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Tr
anscript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">
##INFO=<ID=LOF,Number=.,Type=String,Description="Predicted loss of function effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Per
cent_of_transcripts_affected' ">
##INFO=<ID=NMD,Number=.,Type=String,Description="Predicted nonsense mediated decay effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gen
e | Percent_of_transcripts_affected' ">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
22      17071756        .       T       C       .       .       ANN=C|3_prime_UTR_variant|MODIFIER|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|
c.*11A>G|||||11|,C|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397A>G|||||4223|
22      17072035        .       C       T       .       .       ANN=T|missense_variant|MODERATE|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.1
406G>A|p.Gly469Glu|1666/2034|1406/1674|469/557||,T|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397G>A|
||||3944|
22      17072258        .       C       A       .       .       ANN=A|missense_variant|MODERATE|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.1
183G>T|p.Gly395Cys|1443/2034|1183/1674|395/557||,A|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397G>T|
||||3721|
22      17072674        .       G       A       .       .       ANN=A|missense_variant|MODERATE|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.7
67C>T|p.Pro256Leu|1027/2034|767/1674|256/557||,A|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397C>T|||
||3305|
22      17072747        .       T       C       .       .       ANN=C|missense_variant|MODERATE|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.6
94A>G|p.Met232Val|954/2034|694/1674|232/557||,C|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397A>G||||
|3232|
22      17072781        .       C       T       .       .       ANN=T|synonymous_variant|LOW|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.660G
>A|p.Pro220Pro|920/2034|660/1674|220/557||,T|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397G>A|||||31
98|
22      17073043        .       C       T       .       .       ANN=T|missense_variant|MODERATE|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.3
98G>A|p.Arg133Gln|658/2034|398/1674|133/557||,T|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397G>A||||
|2936|
22      17073066        .       A       G       .       .       ANN=G|synonymous_variant|LOW|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.375T
>C|p.Ala125Ala|635/2034|375/1674|125/557||,G|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397T>C|||||29
13|
22      17073119        .       C       T       .       .       ANN=T|missense_variant|MODERATE|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.3
22G>A|p.Val108Met|582/2034|322/1674|108/557||,T|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397G>A||||
|2860|
22      17073131        .       C       T       .       .       ANN=T|missense_variant|MODERATE|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.3
10G>A|p.Gly104Ser|570/2034|310/1674|104/557||,T|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397G>A||||
|2848|
22      17073134        .       C       A       .       .       ANN=A|missense_variant|MODERATE|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.3
07G>T|p.Asp103Tyr|567/2034|307/1674|103/557||,A|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397G>T||||
|2845|
22      17073145        .       T       G       .       .       ANN=G|missense_variant|MODERATE|CCT8L2|ENSG00000198445|transcript|ENST00000359963|protein_coding|1/1|c.2
96A>C|p.Glu99Ala|556/2034|296/1674|99/557||,G|downstream_gene_variant|MODIFIER|FABP5P11|ENSG00000240122|transcript|ENST00000430910|processed_pseudogene||n.*397A>C|||||2
--More--(0%)

**Comment by arq5x** [comment]
It looks like your VCF lacks genotypes. If so, you need to use: ``--no-genotypes``
