### ISSUE TITLE
Updating to 0.17.0 - pip cannot find required version

### ISSUE THREAD

**Issue by schelhorn** [arq5x/gemini#546]
Currently, the automatic bcbio update for GEMINI seems to fail; when running a manual `gemini update` from GEMINI 0.16.3 (as part of the bcbio anaconda installation), I receive an error:

```python
Collecting gemini==0.17.0 (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 22))
  Could not find a version that satisfies the requirement gemini==0.17.0 (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 22)) (from versions: 0.6.2, 0.6.2.1, 0.6.2.2, 0.6.3, 0.6.3.1, 0.6.3.2, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3)
No matching distribution found for gemini==0.17.0 (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 22))
Traceback (most recent call last):
  File "/cluster/software/bcbio_dev/lib/anaconda/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 995, in update_fn
    gemini_update.release(parser, args)
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/gemini/gemini_update.py", line 54, in release
    subprocess.check_call([pip_bin, "install"] + pip_compat + ["-r", url])
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/cluster/software/bcbio_dev/lib/anaconda/bin/pip', 'install', '--allow-external', 'python-graph-core', '--allow-unverified', 'python-graph-core', '--allow-external', 'python-graph-dot', '--allow-unverified', 'python-graph-dot', '-r', 'https://raw.github.com/arq5x/gemini/master/requirements.txt']' returned non-zero exit status 1
```

May this be related to the fact that the latest GEMINI [is not on pypi yet](https://pypi.python.org/pypi/gemini)?

**Comment by arq5x** [comment]
Sorry, you have caught us in the middle of a transition to a new release. I expect it will be completed today.

**Comment by schelhorn** [comment]
Excellent, thank you. Perhaps it may make sense in the future to push the release to pypi first, and only then change https://raw.github.com/arq5x/gemini/master/requirements.txt? Just a thought.

**Comment by arq5x** [comment]
Indeed.

**Comment by arq5x** [comment]
It should work for you now. Sorry for the trouble.

**Comment by schelhorn** [comment]
Thanks, closing.
