### ISSUE TITLE
gemini comp_hets fails when using exac_num (het or homo) columns

### ISSUE THREAD

**Issue by davemcg** [arq5x/gemini#656]
If "exac_num_hom_alt" and/or "exac_num_het" is included in gemini comp_hets --columns, I get the following error. Don't see it with autosomal_recessive, de_novo, mendel_errors, or autosomal_dominant

```
Traceback (most recent call last):
  File "/usr/local/apps/gemini/0.18/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1177, in main
    args.func(parser, args)
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 690, in comp_hets_fn
    CompoundHet(args).run()
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 279, in run
    for i, s in enumerate(self.report_candidates()):
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 189, in report_candidates
    for gene, li in self.candidates():
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 426, in candidates
    alt1=site1.row['alt'],
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 434, in __getitem__
    return self.row[key]
IndexError: No item with that key
```

**Comment by brentp** [comment]
Thanks for reporting. can you show the full command you are using?

**Comment by davemcg** [comment]
gemini comp_hets \
	--columns "filter, impact, impact_severity, type, chrom,start,end, aaf_1kg_all, aaf_exac_all, exac_num_hom_alt, exac_num_het, codon_change, aa_change, vep_hgvsp, gerp_bp_score, polyphen_score, cadd_raw, sift_pred, sift_score, vep_grantham, (gt_depths).(*)" \
	CCGO_42-44.db --filter "max_aaf_all < 0.01 AND (is_coding=1 OR is_splicing=1)" \
--gt-pl-max 10 -d 5 --min-gq 20 --max-priority 2 | less -S

**Comment by davemcg** [comment]
Re-running the above command but deleting "exac_num_hom_alt" and/or "exac_num_het" causes no problems.

**Comment by brentp** [comment]
what does:
```
gemini query -q "select exac_num_hom_alt, exac_num_hom_alt from variants limit 10" CCGO_42-44.db
```
show?

**Comment by davemcg** [comment]
gemini query -q "select exac_num_hom_alt, exac_num_hom_alt from variants limit 10" CCGO_42-44.db
-1	-1
-1	-1
-1	-1
-1	-1
-1	-1
-1	-1
-1	-1
-1	-1
-1	-1
-1	-1

**Comment by brentp** [comment]
I'm looking into it.

**Comment by brentp** [comment]
I'll push a fix for this shortly.
