### ISSUE TITLE
mendel_errors fails when using --families

### ISSUE THREAD

**Issue by davemcg** [arq5x/gemini#664]
```
Traceback (most recent call last):
  File "/usr/local/apps/gemini/0.18/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1177, in main
    args.func(parser, args)
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 894, in mendel_fn
    MendelViolations(args).run()
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 279, in run
    for i, s in enumerate(self.report_candidates()):
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 175, in report_candidates
    for k, mask in mdict.items():
AttributeError: 'str' object has no attribute 'items'
```

Apologies if this is a dup. I vaguely recall someone else mentioning this issue, but I can't find it.

**Comment by brentp** [comment]
can you report the full query that you are using?

**Comment by davemcg** [comment]
```
gemini de_novo --columns "chrom, start, end" --families CCGO_FAM_800044 CCGO_800014-161.bwa-mem.hg19.GATK.gemini.db | less -S
```
The above works just fine.

However:

```
gemini mendel_errors --columns "chrom, start, end" --families CCGO_FAM_800044 CCGO_800014-161.bwa-mem.hg19.GATK.gemini.db | less -S
```

Gives me this:
```
Traceback (most recent call last):
  File "/usr/local/apps/gemini/0.18/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1177, in main
    args.func(parser, args)
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 894, in mendel_fn
    MendelViolations(args).run()
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 279, in run
    for i, s in enumerate(self.report_candidates()):
  File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 175, in report_candidates
    for k, mask in mdict.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by brentp** [comment]
This is fixed in master. Thanks for reporting.
