### ISSUE TITLE
multi_future Import Error

### ISSUE THREAD

**Issue by AndrewSkelton** [arq5x/gemini#741]
Hi, After resolving all the Python dependancies I get the following error and can't seem to figure out how to get around it. 

```
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 5, in <module>
    pkg_resources.run_script('gemini==.0.19.0-dev', 'gemini')
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 467, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 1200, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/gemini-.0.19.0_dev-py2.7.egg/EGG-INFO/scripts/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/usr/local/lib/python2.7/dist-packages/gemini-.0.19.0_dev-py2.7.egg/gemini/gemini_main.py", line 1227, in main
    args.func(parser, args)
  File "/usr/local/lib/python2.7/dist-packages/gemini-.0.19.0_dev-py2.7.egg/gemini/gemini_main.py", line 197, in load_fn
    import gemini_load
  File "/usr/local/lib/python2.7/dist-packages/gemini-.0.19.0_dev-py2.7.egg/gemini/gemini_load.py", line 10, in <module>
    from cluster_helper.cluster import cluster_view
  File "/usr/local/lib/python2.7/dist-packages/ipython_cluster_helper-0.5.1-py2.7.egg/cluster_helper/cluster.py", line 23, in <module>
    from ipyparallel import Client
  File "/usr/local/lib/python2.7/dist-packages/ipyparallel-5.0.1-py2.7.egg/ipyparallel/__init__.py", line 17, in <module>
    from .client.asyncresult import *
  File "/usr/local/lib/python2.7/dist-packages/ipyparallel-5.0.1-py2.7.egg/ipyparallel/client/asyncresult.py", line 15, in <module>
    from tornado.gen import multi_future
ImportError: cannot import name multi_future
```

Any advice is greatly appreciated!

**Comment by brentp** [comment]
how did you install gemini?

**Comment by AndrewSkelton** [comment]
It seems as though my Python install was messed up in some way, not Gemini at fault!

**Comment by emuchogu** [comment]
Getting the same issue running ipyparallel on ubuntu 14. 
How did you fix it?

**Comment by emuchogu** [comment]
Fixed it with the following:

apt-get remove ipython
apt-get remove python-tornado
pip uninstall ipython
pip uninstall ipyparallel
pip uninstall tornado

rm -rf  /usr/local/lib/python2.7/dist-packages/ipy*
rm -rf  /usr/local/lib/python2.7/dist-packages/tornado*

pip install tornado
pip install ipython
pip install ipython_genutils
pip install ipyparallel
