### ISSUE TITLE
zlib.error: Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by komalsrathi** [arq5x/gemini#745]
Hi,

I created a gemini db as follows:

**Commands**:

```
vcfanno -p 4 -base-path $GEMINI_ANNO -lua test.lua test.conf $VCF | bgzip -c > anno.vcf.gz

# this vcf has been decomposed, normalized using vt and annotated using snpeff
echo $VCF
sample.ad.de.nm.snpeff.vcf

gemini_python $VCF2DB/vcf2db.py anno.vcf.gz $PEDFILES/sample.pedfile my.db
```

I can query it as follows:
```
gemini query -q "select * from variants" --header my.db | head -n2

variant_id	chrom	start	end	vcf_id	ref	alt	qual	filter	type	sub_type	call_rate	num_hom_ref	num_het	num_hom_alt	aaf	hwe	inbreeding_coef	pi	gene	transcript	is_exonic	is_coding	is_lof	is_splicing	exon	codon_change	aa_change	aa_length	biotype	impact	impact_so	impact_severity	polyphen_pred	polyphen_score	sift_pred	sift_score	an	baseqranksum	clippingranksum	db	dp	ds	fs	haplotypescore	inbreedingcoeff	lof	mq	mqranksum	nmd	old_multiallelic	old_variant	qd	readposranksum	sor	af_exac_all	an_exac_all	set
1	chr1	17384	17385	None	G	A	183.399993896	None	snp	ts	1.0	0	2	1	0.666666666667	None	None	None	MIR6859-1	ENST00000619216	1	0	0	0	1			None	miRNA	exon_variant	exon_variant	LOW	None	None	None	None	6	1.45000004768	-1.03600001335	None	23	None	0.0	None	None	None	48.2799987793	-1.03600001335	None	None	None	14.1099996567	0.633000016212	0.836000025272	0.24545408.0	None
```

But I am getting the following error when using the subcommands `autosomal_recessive`, `de_novo`, `comp_hets`. The command `autosomal_dominant` does not give any error or output. 

```
gemini autosomal_recessive my.db
gemini comp_hets my.db
gemini de_novo my.db

Traceback (most recent call last):
  File "/mnt/isilon/cbmi/variome/bin/gemini/tools/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
    args.func(parser, args)
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 851, in autosomal_recessive_fn
    AutoRec(args).run()
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 282, in run
    for i, s in enumerate(self.report_candidates()):
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 192, in report_candidates
    for gene, li in self.candidates():
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 296, in candidates
    for g, li in self.gen_candidates('gene'):
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 105, in gen_candidates
    for grp_key, grp in it.groupby(self.gq, group_key):
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 752, in next
    if row[col] is not None:
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 437, in __getitem__
    self.cache[key] = compression.unpack_genotype_blob(self.row[key])
  File "/mnt/isilon/cbmi/variome/bin/gemini/data/anaconda/lib/python2.7/site-packages/gemini/compression.py", line 15, in unpack_genotype_blob
    return cPickle.loads(zlib.decompress(blob))
zlib.error: Error -3 while decompressing data: incorrect header check
```

I don't really understand what does the error mean, let me know if I can provide more information.

**Comment by brentp** [comment]
Thanks for trying otu the new loader!
you will need to install gemini from github in order to have compatibility with the new loader.

You can do this by checking out this repo and then running python setup.py install (where python is your gemini python).

**Comment by komalsrathi** [comment]
Thanks. I'll give that a try and let you know how it goes.

**Comment by brentp** [comment]
you could also use vcf2db.py with "--legacy-compression" so it will be compatible with current gemini.

**Comment by komalsrathi** [comment]
Awesome! It worked. Thanks!
