### ISSUE TITLE
Gemini installation: ipython-cluster-helper requirement issue

### ISSUE THREAD

**Issue by OvoiDs** [arq5x/gemini#753]
Hi,

I have tried to install gemini on my personnal computer yesterday.
I am having troubles running gemini:

```
11:41:31 boursin@Decima ~ % gemini load
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2900, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2886, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 644, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipython<5.0.0,>=4.0.0' distribution was not found and is required by ipython-cluster-helper
```

```
11:42:29 boursin@Decima ~ % ipython2 --version
4.2.0
```

```
11:43:34 boursin@Decima ~ % pip install ipython-cluster-helper
Requirement already satisfied (use --upgrade to upgrade): ipython-cluster-helper in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): ipyparallel>=4.0.0 in /usr/local/lib/python3.5/dist-packages (from ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): ipython<5.0.0,>=4.0.0 in /usr/local/lib/python3.5/dist-packages (from ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=18.5 in /usr/local/lib/python3.5/dist-packages (from ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): netifaces>=0.10.3 in /usr/local/lib/python3.5/dist-packages (from ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=2.1.11 in /usr/local/lib/python3.5/dist-packages (from ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): jupyter-client in /usr/local/lib/python3.5/dist-packages (from ipyparallel>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): ipykernel in /usr/local/lib/python3.5/dist-packages (from ipyparallel>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/lib/python3.5/dist-packages (from ipyparallel>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4 in /usr/local/lib/python3.5/dist-packages (from ipyparallel>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /usr/local/lib/python3.5/dist-packages (from ipyparallel>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): backports.shutil-get-terminal-size in /usr/local/lib/python3.5/dist-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): pickleshare in /usr/local/lib/python3.5/dist-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): traitlets in /usr/local/lib/python3.5/dist-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): pexpect; sys_platform != "win32" in /usr/local/lib/python3.5/dist-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /usr/lib/python3/dist-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): jupyter-core in /usr/local/lib/python3.5/dist-packages (from jupyter-client->ipyparallel>=4.0.0->ipython-cluster-helper)
Requirement already satisfied (use --upgrade to upgrade): ptyprocess>=0.5 in /usr/local/lib/python3.5/dist-packages (from pexpect; sys_platform != "win32"->ipython<5.0.0,>=4.0.0->ipython-cluster-helper)
```

Do you have any thoughts regarding that issue ?

**Comment by chapmanb** [comment]
Yannick;
Sorry about the issues. Can you provide some details about how you installed gemini?

Practically, you're showing us two different installations with Python 2.7 for GEMINI in the first error:
```
/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py
```
and Python 3.5 when looking for IPython:
```
ipython-cluster-helper in /usr/local/lib/python3.5/dist-packages
```
IPython needs to be installed in the 2.7 environment for GEMINI to use it. The automated installer adds all the dependencies in an isolated Python, instead of your system Python, to avoid these type of issues:

http://gemini.readthedocs.io/en/latest/#new-installation

Hope this helps.

**Comment by OvoiDs** [comment]
Hi Brad,

this helped indeed. It seems like my pip2 was corrupted to use pypy 2.7 instead of python 2.7. Re-installing the dependencies using python 2.7 version of pip solved my issue. 

I had to use a conda-free installation procedure because conda wouldn't work. I have not used a virtualenv, though I have no real reason not using one, it just isn't a reflex for me.

Thank you for your help.
