### ISSUE TITLE
Error while VCF file load

### ISSUE THREAD

**Issue by peterzt** [arq5x/gemini#754]
Greetings,

I'm getting the following error when loading the file:

Traceback (most recent call last):
  File "/home/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/mnt/data/refData/geminiData/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/mnt/data/refData/geminiData/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 197, in load_fn
    gemini_load.load(parser, args)
  File "/mnt/data/refData/geminiData/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 52, in load
    load_singlecore(args)
  File "/mnt/data/refData/geminiData/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 66, in load_singleco
re
    gemini_loader.populate_from_vcf()
  File "/mnt/data/refData/geminiData/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 140, in popula
te_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/mnt/data/refData/geminiData/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 313, in _prepa
re_variation
    call_rate = var.call_rate
  File "cyvcf/parser.pyx", line 506, in cyvcf.parser._Record.call_rate (cyvcf/parser.c:10290)
ZeroDivisionError: float division

Can you please tell what is wrong with my source file? I'm attaching it here.

[prob-file-p3.vcf.gz](https://github.com/arq5x/gemini/files/343249/prob-file-p3.vcf.gz)

Thanks in advance
Peter

**Comment by peterzt** [comment]
My VCF file was malformed, one header line was incorrect
