### ISSUE TITLE
error upgrading to v0.19.0

### ISSUE THREAD

**Issue by susanchacko** [arq5x/gemini#758]
Hi,
I had a previous installation of Gemini 0.18.3, which worked ok, but am having trouble updating to v0.19.0. The update proceeded without errors, but 'bash master_test.sh' gives me the errors below. Any suggestions? I've tried 'gemini update; gemini --data update' but am still getting the same error. 

[W::vcf_parse] INFO 'EPR' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'SOMATIC' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'VT' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'BQ' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'FREQ' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'SS' is not defined in the header, assuming Type=String
pid 10911: 1 variants processed.
pid 10909: 9 variants processed.
pid 10908: 2 variants processed.
storing version, header, etc.
storing version, header, etc.
storing version, header, etc.
pid 10910: 22 variants processed.
storing version, header, etc.
[W::vcf_parse] contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] contig '5' is not defined in the header. (Quick workaround: index the file with tabix.)
Traceback (most recent call last):
File "/usr/local/apps/gemini/0.19.0/bin/gemini", line 6, in <module>
gemini.gemini_main.main()
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
args.func(parser, args)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
gemini_load.load(parser, args)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 50, in load
l = load_singlecore(args)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 85, in load_singlecore
l.populate_from_vcf()
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
(variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 397, in _prepare_variation
Exac = annotations.get_exac_info(var)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 809, in get_exac_info
num_hets = int(info_map.get("AC_Het", -1))
ValueError: invalid literal for int() with base 10: '1477,15508,689,2060,2683,819,388,6,2,34,1,96,211,175,76,36,61,2,78,4,22'
[W::vcf_parse] contig '9' is not defined in the header. (Quick workaround: index the file with tabix.)
Traceback (most recent call last):
File "/usr/local/apps/gemini/0.19.0/bin/gemini", line 6, in <module>
gemini.gemini_main.main()
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
args.func(parser, args)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
gemini_load.load(parser, args)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 50, in load
l = load_singlecore(args)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 85, in load_singlecore
l.populate_from_vcf()
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
(variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 397, in _prepare_variation
Exac = annotations.get_exac_info(var)
File "/fdb/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 809, in get_exac_info
num_hets = int(info_map.get("AC_Het", -1))
ValueError: invalid literal for int() with base 10: '13904,285,15,24,22,2,71,5,153,6,2,0,0,0,0,0,0,0,0,0,0'

**Comment by brentp** [comment]
you must have an old version of ExAC vcf. I would fix by going to your gemini data directory and then doing:
```
rm ExAC*
wget https://s3.amazonaws.com/gemini-annotations/ExAC.r0.3.sites.vep.tidy.vcf.gz
wget https://s3.amazonaws.com/gemini-annotations/ExAC.r0.3.sites.vep.tidy.vcf.gz.tbi
```

sorry we don't have a better solution for this now. I can't figure out why it's not updated.

**Comment by susanchacko** [comment]
Thanks, that worked, and 'bash master_test.sh' ran to completion! 

Susan

**Comment by brentp** [comment]
great! thanks for following up. I will close this issue as we are tracking the stale ExAC file in another issue.
