### ISSUE TITLE
UnicodeEncodeError while creating gemini DB

### ISSUE THREAD

**Issue by rdocking** [arq5x/gemini#808]
Hi there,

  Thanks for making gemini available! I've been having some trouble getting my variants loaded. I've been running gemini on linux as part of the bcbio-nextgen pipeline. The bundled version is:

```
> /projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/bin/gemini --version
gemini 0.19.1
```

  When I run the bcbio variant-calling pipeline, it generates a `gemini load` command like (in Make syntax):

```
$(GEMINI) load \
  --passonly --skip-gene-tables --skip-gerp-bp \
  -v $(VCF_INPUT) \
  -t VEP --cores 8 \
  $(VCF_OUTPUT)
```

 When I run this, I get Unicode errors like this:

```
Traceback (most recent call last):
  File "/projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
    args.func(parser, args)
  File "/projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
    gemini_load.load(parser, args)
  File "/projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 50, in load
    l = load_singlecore(args)
  File "/projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 84, in load_singlecore
    l = GeminiLoader(args)
  File "/projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 126, in __init__
    self.clinvar_chrom_gene_lookup = load_clinvar(annotations.get_anno_files(self.args)['clinvar'])
  File "/projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 72, in load_clinvar
    diseases = [x.decode('utf8', 'ignore').encode('ascii', 'ignore') for x in info.get('CLNDBN').split("|") if not x in (".", "not_specified", "not_provided")]
  File "/projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 8: ordinal not in range(128)
make: *** [data/A08822-ensemble.db] Error 1
```

Can you help me debug this? Thanks!

**Comment by brentp** [comment]
Yes, see this recent bcbio thread: https://github.com/chapmanb/bcbio-nextgen/issues/1781#issuecomment-274570067

This is fixed in gemini master so you can git clone this repo and then run `python setup.py install`. Or wait for the bcbio update.

**Comment by rdocking** [comment]
Great - thanks! I'll update from GitHub and follow along on the bcbio issue. Thanks for your help - I'll close this issue.

**Comment by brentp** [comment]
ok. let me know if you have any other issues.

**Comment by mmoisse** [comment]
I have just the opposite error, but I can fix it when I uncomment line 73 and comment line 74 in gemini_load_chunk.py

    diseases = [x.decode('utf8', 'ignore').encode('ascii', 'ignore') for x in info.get('CLNDBN').split("|") if not x in (".", "not_specified", "not_provided")]
    #diseases = [x.encode('ascii', 'ignore').decode('ascii', 'ignore') for x in info.get('CLNDBN').split("|") if not x in (".", "not_specified", "not_provided")]

The error:

    $ gemini load -v chrTest5.flt.norm.VEP.vcf.gz -t VEP --core 1 chrTest5.flt.norm.VEP.db                                                       
    CADD scores are being loaded (to skip use:--skip-cadd).
    GERP per bp is being loaded (to skip use:--skip-gerp-bp).
    Traceback (most recent call last):
      File "/software/gemini/gemini.git/bin/gemini", line 7, in <module>
        gemini_main.main()
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1232, in main
        args.func(parser, args)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 200, in load_fn
        gemini_load.load(parser, args)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
        l = load_singlecore(args)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 85, in load_singlecore
        l = GeminiLoader(args)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 128, in __init__
        self.clinvar_chrom_gene_lookup = load_clinvar(annotations.get_anno_files(self.args)['clinvar'])
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 74, in load_clinvar
        diseases = [x.encode('ascii', 'ignore').decode('ascii', 'ignore') for x in info.get('CLNDBN').split("|") if not x in (".", "not_specified", "not_provided")]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)

**Comment by brentp** [comment]
You'll have to update both gemini and cyvcf2

**Comment by mmoisse** [comment]
And this is not done by `gemini update --devel` I presume?

**Comment by brentp** [comment]
you'll have to update cyvcf2 manually.

**Comment by chapmanb** [comment]
I pushed a fix so in the future (after a successful `--devel` upgrade) it will now also update the cyvcf2 conda package so hopefully we can avoid this issue in the future. Thanks for the feedback and testing on this.
