### ISSUE TITLE
gemini annotate -f file.vcf.gz - sqlalchemy.exc.StatementError

### ISSUE THREAD

**Issue by mmoisse** [arq5x/gemini#809]
I'm trying to add custom annotation from vcf to my db, but I get the following error (see below).
I'm using version 0.19.1, but if I use version 0.18.0 I don't get this error. Can it has something to do with the use of sqlalchemy in the newer version?

    $ gemini annotate -f file.vcf.gz -a extract -t text,text,text -c ADM_ID,ADM_PATH,ADM_NAME -e ID,PATH,NAME -o list,list,list gemini.db
    Traceback (most recent call last):
      File "/software/gemini/gemini.git/bin/gemini", line 6, in <module>
        gemini.gemini_main.main()
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
        args.func(parser, args)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 620, in annotate_fn
        gemini_annotate.annotate(parser, args)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_annotate.py", line 360, in annotate
        annotate_variants_extract(args, conn, metadata, col_names, col_types, col_ops, col_idxs)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_annotate.py", line 281, in annotate_variants_extract
        col_names, col_types, col_ops)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_annotate.py", line 117, in _annotate_variants
        _update_variants(metadata, to_update, col_names, cursor)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_annotate.py", line 135, in _update_variants
        cursor.execute(stmt, [mkdict(v) for v in to_update])
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
        return meth(self, multiparams, params)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
        None, None)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
        exc_info
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
        context = constructor(dialect, self, conn, *args)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 589, in _init_compiled
        self.compiled_parameters = [compiled.construct_params()]
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 547, in construct_params
        % bindparam.key)
    sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter '_ADM_ID' [SQL: u'UPDATE variants SET "ADM_ID"=?, "ADM_PATH"=?, "ADM_NAME"=? WHERE variants.variant_id = ?']

**Comment by mmoisse** [comment]
I just tried gemini 0.20.0, but then I get in some kind of infinite loop with database never getting annotated. When I force quit it I get the following error:

    Traceback (most recent call last):
      File "/software/gemini/gemini.git/bin/gemini", line 7, in <module>
        gemini_main.main()
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1232, in main
        args.func(parser, args)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 625, in annotate_fn
        gemini_annotate.annotate(parser, args)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_annotate.py", line 366, in annotate
        annotate_variants_extract(args, conn, metadata, col_names, col_types, col_ops, col_idxs)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_annotate.py", line 287, in annotate_variants_extract
        col_names, col_types, col_ops)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/gemini/gemini_annotate.py", line 100, in _annotate_variants
        for row in select_res.fetchmany(CHUNK_SIZE):
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1155, in fetchmany
        self.cursor, self.context)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1396, in _handle_dbapi_exception
        util.reraise(*exc_info)
      File "/software/gemini/gemini.git/share/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1148, in fetchmany
        l = self.process_rows(self._fetchmany_impl(size))

**Comment by brentp** [comment]
can you share some data that reproduces the problem? e.g. with a small subset of the original vcf and then of hte annotation file?

**Comment by mmoisse** [comment]
Please find attached a test file

[ADMutations.vcf.gz](https://github.com/arq5x/gemini/files/727138/ADMutations.vcf.gz)
[ADMutations.vcf.gz.tbi.zip](https://github.com/arq5x/gemini/files/727146/ADMutations.vcf.gz.tbi.zip)
[projectMinE.merged.20160715.chrTestX.flt.norm.VEP.db.zip](https://github.com/arq5x/gemini/files/727140/projectMinE.merged.20160715.chrTestX.flt.norm.VEP.db.zip)

**Comment by brentp** [comment]
thanks for the test-case. I pushed a fix for this. It was a bad bug where gemini annotate wouldn't terminate in some cases.
