### ISSUE TITLE
Error in master test

### ISSUE THREAD

**Issue by valeriouberti** [arq5x/gemini#835]
Hello! 
I'm new with GEMINI! I tried to install it and everithing is ok, but when I try to run the master_test.sh or I try to load a vcf file i have this error:
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1232, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 197, in load_fn
    from gemini import gemini_load
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 9, in <module>
    from gemini import annotations
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 4, in <module>
    import pysam
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory

Thanks, Valerio

**Comment by brentp** [comment]
can you do `conda remove pysam` and then `conda install -c bioconda pysam`
and try again?

**Comment by chapmanb** [comment]
The underlying cause of this issue is that pysam isn't yet compatible with the latest htslib release (1.4). You can fix manually with:
```
conda install -c bioconda htslib '>=1.3,<1.4'
```
Hope this helps.

**Comment by valeriouberti** [comment]
I tried to` conda remove pysam` and `conda install -c bioconda pysam` but I have the same error. Is it possible that error is caused because anaconda is in a different folder then the installation of GEMINI?

**Comment by valeriouberti** [comment]
I fixed doing the downgrade of hhtslib at the 1.3 version.

Thanks!
