### ISSUE TITLE
Change (UPDATE) sample name (v0.19.1)

### ISSUE THREAD

**Issue by VelNZ** [arq5x/gemini#846]
Hey,

I need to change a sample name in a database and the standard UPDATE samples SET name = "new_name" WHERE name = "current_name" gives me Python errors.

Here's the full query:
```
gemini query -q "UPDATE samples SET name = \"new_name\" WHERE name = \"old_name\"" dbfilename.db
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 422, in query_fn
    gemini_query.query(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_query.py", line 167, in query
    run_query(args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_query.py", line 133, in run_query
    gene_needed, args.show_families, subjects=subjects)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 638, in run
    self.result_proxy = res = iter(self._apply_query())
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 909, in _apply_query
    self.all_query_cols = [str(tuple[0]) for tuple in res.cursor.description
AttributeError: 'NoneType' object has no attribute 'description'
```

I'm running GEMINI v0.19.1 and I remember when I used to have 0.15 installed I could update the sample names with that query even though I would get a Python error; now I get the error and no update occurs.

Any ideas?

**Comment by brentp** [comment]
just run that directly through sqlite:

`echo "UPDATE samples SET name = \"new_name\" WHERE name = \"old_name\"" | sqlite3 $db`

**Comment by VelNZ** [comment]
Brilliant thanks, I had tried using sqlite directly on the database and had a "Unable to open database "filename.db": file is encrypted or is not a database" error but your solution worked!

**Comment by brentp** [comment]
no problem. it's actually a bug that this isn't supported in gemini, but seems to be rarely hit.
