### ISSUE TITLE
How to install version 0.19.1 ?

### ISSUE THREAD

**Issue by ehenrion** [arq5x/gemini#850]
Hi there,
Is there a way to install gemini version 0.19.1 ?
I know it might seems awkward but I have to maintain multiple installed versions, and I recently noticed that my gemini 0.19.1 was actually pointing to gemini 0.20.0...

I tried the following :
`python gemini_install.py --nodata path/to/gemini/gemini-0.19.1 path/to/gemini/gemini-0.19.1/shared
path/to/gemini/gemini-0.19.1/shared/anaconda/bin/pip install -r requirements.txt`
I got the _requirement.txt_ file by cloning your repository.
I can't get pass this error : 
> Collecting gemini==0.19.1 (from -r requirements.txt (line 23))
>   Could not find a version that satisfies the requirement gemini==0.19.1 (from -r requirements.txt (line 23)) (from versions: 0.6.2, 0.6.2.1, 0.6.2.2, 0.6.3, 0.6.3.1, 0.6.3.2, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.18.2, 0.18.3)
> No matching distribution found for gemini==0.19.1 (from -r requirements.txt (line 23))

Also note that this work perfectly for older versions.

I also tried : 
`python gemini_install.py --gemini-version 0.19.1 path/to/gemini/gemini-0.19.1 path/to/gemini/gemini-0.19.1/shared`
but this also didn't work :
> Checking required dependencies...
>  wget found
> Installing isolated base python installation
> Installing base gemini package...
>  path/to/gemini/gemini-0.19.1/shared/anaconda/bin/conda install --yes -c conda-forge -c bioconda --file _conda-requirements-0.19.1.txt
> Fetching package metadata .............
> 
> PackageNotFoundError: Package missing in current linux-64 channels: 
>   - gemini 0.19.0 py27_2
> 
> Traceback (most recent call last):
>   File "gemini_install.py", line 191, in <module>
>     main(parser.parse_args())
>   File "gemini_install.py", line 83, in main
>     gemini = install_conda_pkgs(anaconda, remotes, args)
>   File "gemini_install.py", line 105, in install_conda_pkgs
>     subprocess.check_call([anaconda["conda"], "install", "--yes"] + channels + pkgs)
>   File " path/to/python/Python-2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[' path/to/gemini/gemini-0.19.1/shared/anaconda/bin/conda', 'install', '--yes', '-c', 'conda-forge', '-c', 'bioconda', '--file', '_conda-requirements-0.19.1.txt']' returned non-zero exit status 1

Any idea on how to get through this ?

Thanks !

**Comment by ehenrion** [comment]
I mean... Thanks a lot...

**Comment by brentp** [comment]
I'm not sure how to debug this. Are you still neededing 0.19.1? I think you could try:

conda install -c bioconda gemini=0.19.1

**Comment by ehenrion** [comment]
Yes !

It worked : had to install the latest version and then run the command you gave me to downgrade the version to 0.19.1.

Thanks a lot !

Regards,
