### ISSUE TITLE
Error while loading VCF

### ISSUE THREAD

**Issue by kpalanikannan** [arq5x/gemini#854]
Hi,

Can any one help to track the issue with the error below?

Loading chunk 0.
Loading chunk 1.
Loading chunk 2.
Loading chunk 3.
Loading chunk 4.
Loading chunk 5.
Loading chunk 6.
Loading chunk 7.
Loading chunk 8.
Loading chunk 9.
Loading chunk 10.
Loading chunk 11.
Loading chunk 12.
Loading chunk 13.
Loading chunk 14.
Loading chunk 15.
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
      File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    fields[5] = l.get(fields[5].lower(), fields[5])
    self._prepare_samples()
IndexError  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
: list index out of range
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_load_chunk.load(parser, args)
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    gemini_loader = GeminiLoader(args)
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError    : fields[5] = l.get(fields[5].lower(), fields[5])
list index out of rangeIndexError: list index out of range

    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 910, in load
    gemini_loader = GeminiLoader(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 132, in __init__
    self._prepare_samples()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 770, in _prepare_samples
    self.ped_hash = load_ped_file(self.args.ped_file)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 36, in load_ped_file
    fields = _fix_ped_affected(fields)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 48, in _fix_ped_affected
    fields[5] = l.get(fields[5].lower(), fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/palani.k/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 204, in load_fn
    gemini_load.load(parser, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 49, in load
    load_multicore(args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 93, in load_multicore
    chunks = load_chunks_multicore(grabix_file, args)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 264, in load_chunks_multicore
    wait_until_finished(procs)
  File "/MGMSTAR1/SHARED/ANALYSIS/RESOURCES/Tools/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 359, in wait_until_finished
    raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load

**Comment by brentp** [comment]
hi, does your ped file have 6 columns for all rows?
