### ISSUE TITLE
Actionable mutation and dgidb issue

### ISSUE THREAD

**Issue by robrollback** [arq5x/gemini#871]
Hi, 

Seems to be a new issue regarding actionable mutation function and it's interaction with dgidb.

Any help would be much appreciated.

Using gemini 0.20.1 and tested on two separate clusters.

Error:
Traceback (most recent call last):
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1232, in main
    args.func(parser, args)
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1049, in get_actionable_mut_fn
    gemini_actionable_mutations.get_actionable_mutations(parser, args)
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/site-packages/gemini/gemini_actionable_mutations.py", line 35, in get_actionable_mutations
    dgidb_info = query_dgidb(genes)
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/site-packages/gemini/dgidb.py", line 34, in query_dgidb
    response = urlopen(query)
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/cvmfs/soft.mugqic/CentOS6/software/gemini/shared/anaconda/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 308: Permanent Redirect

Best,
 Rob E.

**Comment by cailing20** [comment]
I think I have a related issue too:

Traceback (most recent call last):
  File "/cm/shared/apps/gemini/0.20.1/bin/gemini", line 4, in <module>
    __import__('pkg_resources').run_script('gemini==0.20.1', 'gemini')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/cm/shared/apps/gemini/0.20.1/lib/python2.7/site-packages/gemini-0.20.1-py2.7.egg/EGG-INFO/scripts/gemini", line 7, in <module>
    gemini_main.main()
  File "/cm/shared/apps/gemini/0.20.1/lib/python2.7/site-packages/gemini-0.20.1-py2.7.egg/gemini/gemini_main.py", line 1248, in main
    args.func(parser, args)
  File "/cm/shared/apps/gemini/0.20.1/lib/python2.7/site-packages/gemini-0.20.1-py2.7.egg/gemini/gemini_main.py", line 1065, in get_actionable_mut_fn
    gemini_actionable_mutations.get_actionable_mutations(parser, args)
  File "/cm/shared/apps/gemini/0.20.1/lib/python2.7/site-packages/gemini-0.20.1-py2.7.egg/gemini/gemini_actionable_mutations.py", line 35, in get_actionable_mutations
    dgidb_info = query_dgidb(genes)
  File "/cm/shared/apps/gemini/0.20.1/lib/python2.7/site-packages/gemini-0.20.1-py2.7.egg/gemini/dgidb.py", line 34, in query_dgidb
    response = urlopen(query)
  File "/cm/shared/apps/python/2.7.x-anaconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/cm/shared/apps/python/2.7.x-anaconda/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/cm/shared/apps/python/2.7.x-anaconda/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/cm/shared/apps/python/2.7.x-anaconda/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/cm/shared/apps/python/2.7.x-anaconda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/cm/shared/apps/python/2.7.x-anaconda/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 308: Permanent Redirect

**Comment by brentp** [comment]
The interface and URL for dgidb have changed. I'd accept a pull request to update to the new version.
