### ISSUE TITLE
gemini web browser error

### ISSUE THREAD

**Issue by jpdna** [arq5x/gemini#876]
Hi, GEMINI is a great tool! 
We'd like to use and possibly extend the web-browser for local needs.

I have a gemini database that works fine for `gemini query` command line access.

I am able to start the built in browsers like:
```
gemini browser AGV_trio1.db --use builtin
```
But when I click on "Submit" for a query in the web borwser, I get the following error about `database disk image malformed` in the browser window and at the terminal running the webserver:
```
HG-01931188-LM1:test2 paschalj$ gemini browser AGV_trio1.db --use builtin
Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://localhost:8088/
Hit Ctrl-C to quit.

/Users/paschalj/install_gemini/anaconda/bin/bottle.py:3325: DeprecationWarning: Absolute template path names are deprecated.
  fname = self.search(name, self.lookup)
127.0.0.1 - - [09/Nov/2017 09:37:36] "GET / HTTP/1.1" 200 3452
127.0.0.1 - - [09/Nov/2017 09:37:37] "GET /query HTTP/1.1" 200 5680
Traceback (most recent call last):
  File "/Users/paschalj/install_gemini/anaconda/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/paschalj/install_gemini/anaconda/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_browser.py", line 104, in query
    gq = GeminiQuery.GeminiQuery(database)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 548, in __init__
    self._connect_to_database()
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 834, in _connect_to_database
    self.conn, self.metadata = database.get_session_metadata(self.db)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/gemini/database.py", line 561, in get_session_metadata
    metadata.reflect(bind=engine)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3874, in reflect
    bind.engine.table_names(schema, connection=conn))
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2128, in table_names
    return self.dialect.get_table_names(conn, schema)
  File "<string>", line 2, in get_table_names
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 42, in cache
    return fn(self, con, *args, **kw)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1160, in get_table_names
    rs = connection.execute(s)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) database disk image is malformed [SQL: "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"]
127.0.0.1 - - [09/Nov/2017 09:38:24] "GET /query?query=+select+chrom%2C+start%2C+end%2C+ref%2C+alt%2C+gts.sample1+from+variants+limit+10%0D%0A&gt_filter=%28gts.34-0583_S1+%3D%3D+HET%29+&submit=submit HTTP/1.1" 500 4325
127.0.0.1 - - [09/Nov/2017 09:38:45] "GET / HTTP/1.1" 200 3452
```

**Comment by brentp** [comment]
hmm. not sure what this is. could you try:
```
echo "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;" | sqlite3 AGV_trio1.db
```
and share the result?

**Comment by jpdna** [comment]
I get:
```
test1 paschalj$ echo "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;" | sqlite3 AGV_trio1.db
gene_detailed
gene_summary
resources
sample_genotype_counts
sample_genotypes
samples
variant_impacts
variants
vcf_header
version
```

**Comment by brentp** [comment]
I'm afraid I don't have any good ideas. 
can you start the browser with the full path to the database instead of the local path?

you could also try the puzzle browser for gemini.

**Comment by brentp** [comment]
nice! yes. you'll just use `34_0583_S1` as the sample name as gemini converts those on load.

**Comment by jpdna** [comment]
still seems to have trouble with samples ids.
I get:
```
Sorry, the requested URL 'http://localhost:8088/query?query=select+chrom%2C+start%2C+end%2C+ref%2C+alt%2C+gts.sample1+from+variants+limit+10&gt_filter=%28gt_types.34_0583_S1+%3D%3D+HET%29&submit=submit' caused an error:

Traceback (most recent call last):
  File "/Users/paschalj/install_gemini/anaconda/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/paschalj/install_gemini/anaconda/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_browser.py", line 106, in query
    gq.run(query, gt_filter)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 628, in run
    self.gt_filter = self._correct_genotype_filter()
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 1029, in _correct_genotype_filter
    corrected = self._correct_genotype_col(t)
  File "/Users/paschalj/install_gemini/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 948, in _correct_genotype_col
    corrected = "%s[%d]" % (column.lower(), self.sample_to_idx[sample])
KeyError: '34_0583_S1'
```

I took at look at the samples table in sqlite
```
HG-01931188-LM1:test1 paschalj$ echo "SELECT * FROM samples limit 5;" | sqlite3 AGV_trio1.db
1|0|34-0581_S1|0|0|-9|-9
2|0|34-0582_S1|0|0|-9|-9
3|0|34-0583_S1|0|0|-9|-9
```

So you think the underscores are causing the trouble?  
I will try starting with non underscores or hyphen sample names.

Related though - is it strange that leaving the genotype filter query box empty causes an error?

**Comment by brentp** [comment]
as you might guess, you are using a part of gemini that's not very widely used. I think if you remove the "-" then it might resolve the issues.

I just pushed a fix for the empty genotype filter. If you pull from github that should fix that problem at least.
