### ISSUE TITLE
Error when trying to use ped file, or amend it to the DB!

### ISSUE THREAD

**Issue by coolman17** [arq5x/gemini#882]
Hi,

Thanks in advance for your help!

Every time I try to use the pedigree file I get the following message. I had to import the vcf without the ped file, but still can't even amend it now. It is a standard six-column pedigree file.

$ gemini amend --sample famTree.ped all20Samp.db 
Traceback (most recent call last):
  File "/home/ahmed/gemini/tools/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1248, in main
    args.func(parser, args)
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 227, in amend_fn
    gemini_amend.amend(parser, args)
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/site-packages/gemini/gemini_amend.py", line 12, in amend
    amend_sample(args)
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/site-packages/gemini/gemini_amend.py", line 16, in amend_sample
    ped_dict = load_ped_file(args.sample)
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 35, in load_ped_file
    fields = [x.strip() for x in _fix_ped_family_fields(parts)]
  File "/home/ahmed/gemini/tools/anaconda/lib/python2.7/site-packages/gemini/ped.py", line 58, in _fix_ped_family_fields
    if fields[field] in missing_member:
IndexError: list index out of range

**Comment by brentp** [comment]
seems like something might be wrong with your ped file. can you show the output of:
```
awk 'BEGIN{FS="\t"}{ print NF }' famTree.ped | sort | uniq -c
```

**Comment by coolman17** [comment]
Thanks a lot!
I got:

1     0
20   6

But then I checked the "0" line and it was the last one. So I removed it, and voila! it worked. However, upon running 'gemini amend --sample famTree.ped all20Samp.db' again, it took less than 30 seconds to complete... is that normal?

I really appreciate your kind help!

**Comment by brentp** [comment]
yes, it should be pretty much instant. It's just modifying the small samples table with (in your case) 20 rows.

**Comment by coolman17** [comment]
Thanks again... Gemini is such a great tool!
