### ISSUE TITLE
gemini dont work with several cores

### ISSUE THREAD

**Issue by aurelBZH** [arq5x/gemini#888]
I have a problem of multicore loading with gemini 0.20.1, grabix 0.1.8 and python 2.7. 
With 4 cores the gemini load command don't work : 
 `./tools/bin/gemini load --cores 4 -t VEP -v result.vcf.gz test_db.db`

the error message : 

`Indexing /home/aurelien.beliard/varapp/result.vcf.gz with grabix.
Loading 286164 variants.
Breaking /home/aurelien.beliard/varapp/result.vcf.gz into 4 chunks.
Loading chunk 0.
Loading chunk 1.
/bin/sh: 1: gemini: not found
Loading chunk 2.
/bin/sh: 1: gemini: not found
Loading chunk 3.
/bin/sh: 1: gemini: not found
/bin/sh: 1: gemini: not found
Traceback (most recent call last):
  File "./tools/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/home/aurelien.beliard/varapp/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1248, in main
    args.func(parser, args)
  File "/home/aurelien.beliard/varapp/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 204, in load_fn
    gemini_load.load(parser, args)
  File "/home/aurelien.beliard/varapp/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 49, in load
    load_multicore(args)
  File "/home/aurelien.beliard/varapp/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 93, in load_multicore
    chunks = load_chunks_multicore(grabix_file, args)
  File "/home/aurelien.beliard/varapp/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 264, in load_chunks_multicore
    wait_until_finished(procs)
  File "/home/aurelien.beliard/varapp/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 359, in wait_until_finished
    raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load
`
while with one core : 
`./tools/bin/gemini load --cores 1  -t VEP -v result.vcf.gz test_db.db`

it work perfectly

**Comment by brentp** [comment]
Make sure that `gemini` is on your `$PATH` it looks like that is not the case since you are using `/tools/bin/gemini`

**Comment by aurelBZH** [comment]
oh ok i didn't add it to the the path. I don't understand why i can't use it without add it to the path but it work now. 

 thanks for your help
