### ISSUE TITLE
"bash master-test.sh" bugs

### ISSUE THREAD

**Issue by ponomarevsy** [arq5x/gemini#901]
Dear Gemini experts:

We observe the following warnings/errors when running tests in "***gemini-0.20.2.dev0***" release. Please let us know if these warnings/errors are crucial and, if so, how they can be fixed. Thank you in advance!

***System Information:***
```
» conda -V
conda 4.5.10

» python -V
Python 2.7.12

» pip list | grep -i numpy
numpy                              1.14.5

» pip list | grep -i scipy
scipy                              0.12.0

» lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.2 (Maipo)
Release:	7.2
Codename:	Maipo
```
***Warnings/errors we observe:***
```
Traceback (most recent call last):
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/bin/gemini", line 4, in <module>
    __import__('pkg_resources').run_script('gemini==0.20.2.dev0', 'gemini')
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    exec(code, namespace, namespace)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/EGG-INFO/scripts/gemini", line 7, in <module>
    gemini_main.main()
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/gemini_main.py", line 1249, in main
    args.func(parser, args)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/gemini_main.py", line 204, in load_fn
    gemini_load.load(parser, args)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/gemini_load.py", line 51, in load
    l = load_singlecore(args)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/gemini_load.py", line 85, in load_singlecore
    l = GeminiLoader(args)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/gemini_load_chunk.py", line 104, in __init__
    self.vcf_reader = self._get_vcf_reader()
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/gemini_load_chunk.py", line 288, in _get_vcf_reader
    return vcf.VCFReader(self.args.vcf)
  File "cyvcf2/cyvcf2.pyx", line 185, in cyvcf2.cyvcf2.VCF.__init__ (cyvcf2/cyvcf2.c:7089)
Exception: bad path: /path/gemini/test/unicode.vcf.gz
```
```
Requested GEMINI database (unicode.test.db) not found. Please confirm the provided filename.
Error: cannot find annotation file.
```
```
/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/pandas-0.23.4-py2.7-linux-x86_64.egg/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.
```
```
test-cadd.sh: line 6: gemini_python: command not found
test-gerp.sh: line 23: gemini_python: command not found
```
```
    somatic.t02...Traceback (most recent call last):
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/bin/gemini", line 4, in <module>
    __import__('pkg_resources').run_script('gemini==0.20.2.dev0', 'gemini')
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    exec(code, namespace, namespace)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/EGG-INFO/scripts/gemini", line 7, in <module>
    gemini_main.main()
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/gemini_main.py", line 1249, in main
    args.func(parser, args)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/gemini_main.py", line 1066, in get_actionable_mut_fn
    gemini_actionable_mutations.get_actionable_mutations(parser, args)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/gemini_actionable_mutations.py", line 35, in get_actionable_mutations
    dgidb_info = query_dgidb(genes)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/gemini-0.20.2.dev0-py2.7.egg/gemini/dgidb.py", line 34, in query_dgidb
    response = urlopen(query)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 308: Permanent Redirect
```
```
/path/Anaconda/2.3.0Linux-x86_64/envs/geminienv3/lib/python2.7/site-packages/bcolz-1.2.1-py2.7-linux-x86_64.egg/bcolz/chunked_eval.py:264: UserWarning: numexpr cannot handle this expression: falling back to the 'python' virtual machine.  You can choose another virtual machine by using the `vm` parameter.
  "numexpr cannot handle this expression: falling back "
```

**Comment by brentp** [comment]
these have been fixed.
