### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by afkoeppel** [arq5x/gemini#908]
I'm unable to install gemini on our linux server and was hoping for some assistance. I'm using a GNU/Linux server, on which I do not have sudo permission.

I first tried using the recommended installation script:
`wget https://github.com/arq5x/gemini/raw/master/gemini/scripts/gemini_install.py`
`python gemini_install.py ~gemini ~gemini`

It seems to install most of the packages, but then dies with:
`Traceback (most recent call last):
  File "gemini_install.py", line 191, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 84, in main
    install_rest(gemini, args)
  File "gemini_install.py", line 149, in install_rest
    subprocess.check_call(cmd)
OSError: [Errno 2] No such file or directory`

I then attempted to install it directly using conda:
`conda install -c bioconda gemini`
This installation appeared to work fine, but none of the annotation files were installed, and when I tried to install them with (e.g.):
`gemini update --dataonly --extra gerp_bp` I got a permission error:
`OSError: [Errno 13] Permission denied: '/.automount'`

Apologies if this problem already has a posted answer, or if I'm doing something stupid.  None of the other threads I looked at showed this exact problem.  I'm guessing it has something to do with file permissions on my server, but I'm able to write most places other than root.   I don't know what '/.automount' is or why it's trying to write there.

**Comment by afkoeppel** [comment]
Update.  My boss (who has root access) was able to help me get around the second issue by adding a `/.automount` directory which was a symlink to a directory on my account.  I'm now able to update cadd and gerp scores, but I'm still interested to know if this can be done without root access.

**Comment by bgruening** [comment]
@afkoeppel you could use conda to install gemini. See here: https://bioconda.github.io/recipes/gemini/README.html

This works for us quite well.

**Comment by kortschak** [comment]
conda is not working well in all cases:

```
$ conda create -n clinical -c bioconda gemini python=2.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                   

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=2.7
gemini -> bcolz -> python[version='3.4.*|3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5|>=3.6|<3.0.0']
gemini -> python[version='2.7.*|>=2.7,<2.8.0a0']

$ conda info

     active environment : base
    active env location : /home/user/miniconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : 
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __glibc=2.27
       base environment : /home/user/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.4 Linux/4.15.0-76-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

Is this a 2!=3 issue?

**Comment by brentp** [comment]
I would follow the installation instructions here:
https://gemini.readthedocs.io/en/latest/#new-installation

**Comment by kortschak** [comment]
This is for student training machines which have a variety of software installed so I'm avoiding potential for machine breakage. I've gone with a docker image.

**Comment by brentp** [comment]
OK. We are moving to this: https://github.com/brentp/slivar
which has a static binary and a wget of some javascript for installation.

**Comment by kortschak** [comment]
Thanks. I'll look into it.

**Comment by aleksmllr** [comment]
Hello! I am very excited to use Gemini in my current research project. I am trying to install Gemini on my Macbook and I run into the following error.

All requested packages already installed.

/Users/aleks/geminiStuff/data/anaconda/bin/gemini --annotation-dir /Users/aleks/geminiStuff/data/gemini_data update --dataonly --tooldir /Users/aleks/geminiStuff/tools
Traceback (most recent call last):
  File "gemini_install.py", line 191, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 84, in main
    install_rest(gemini, args)
  File "gemini_install.py", line 149, in install_rest
    subprocess.check_call(cmd)
  File "/Users/aleks/anaconda3/envs/geminiEnv/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Users/aleks/anaconda3/envs/geminiEnv/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/aleks/anaconda3/envs/geminiEnv/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Users/aleks/anaconda3/envs/geminiEnv/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I am confused as to what is happening as I created two new directories for the tools and data. I am using the automated gemini_install.py script. I am pretty novice when it comes to commandline tools. My command that produced the above error was: python gemini_install.py ~/geminiStuff/tools ~/geminiStuff/data

I am currenlty trying to install this using a Python 2.7 conda environment. 

If someone could point me in the right direction as to what I'm doing wrong that would be amazing.
