### ISSUE TITLE
error

### ISSUE THREAD

**Issue by handomsu** [arq5x/gemini#920]
gemini load -v sample.raw_variants.vcf -t snpEff my.db
CADD scores are being loaded (to skip use:--skip-cadd).
GERP per bp is being loaded (to skip use:--skip-gerp-bp).
Traceback (most recent call last):
  File "/raid/gemini/tool/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/raid/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1248, in main
    args.func(parser, args)
  File "/raid/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 204, in load_fn
    gemini_load.load(parser, args)
  File "/raid/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
    l = load_singlecore(args)
  File "/raid/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 85, in load_singlecore
    l = GeminiLoader(args)
  File "/raid/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 126, in __init__
    self._create_db([x[0] for x in self._extra_effect_fields])
  File "/raid/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 357, in _create_db
    self.c, self.metadata = database.create_tables(db_path, effect_fields or [], not self.args.skip_pls)
  File "/raid/gemini/data/anaconda/lib/python2.7/site-packages/gemini/database.py", line 394, in create_tables
    e.connect().connection.connection.text_factory = str
pysqlite2.dbapi2.ProgrammingError: Cannot operate on a closed database.
https://github.com/arq5x/gemini/issues

**Comment by brentp** [comment]
I would run `ls my.db*` and `ls -a` to check for .lock files from a previous run that make sqlite think the database is in use.

**Comment by handomsu** [comment]
Thank you, but it doesn't work..
ls -a
.  ..  data  gemini_install.py  my.db  sample.raw_variants.vcf  tool 
rm my.db also doesn't work

**Comment by brentp** [comment]
are you on NFS?
