### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__

### ISSUE THREAD

**Issue by kellogg76** [arq5x/gemini#928]
I'm having an issue running gemini commands that worked just a few weeks ago.

running :-
`gemini load -v ~/FEVR/hg19.snpEff.vcf -t snpEff --cores 8 ~/FEVR/hg19.db`

gives the following error

```
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 204, in load_fn
    gemini_load.load(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 23, in load
    annos = annotations.get_anno_files(args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 23, in get_anno_files
    anno_dirname = config["annotation_dir"]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

If I try to run gemini update, I get :-
```
Collecting package metadata: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /usr/local/share/gemini/anaconda/pkgs/cache/4ea078d6.json
  uid: 1003
  gid: 1004

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 1003:1004 /usr/local/share/gemini/anaconda/pkgs/cache/4ea078d6.json

In general, it's not advisable to use 'sudo conda'.


Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1085, in update_fn
    gemini_update.release(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_update.py", line 23, in release
    "gemini", "cyvcf2", "pip"])
  File "/usr/local/share/gemini/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/gemini/anaconda/bin/conda', 'install', '-y', '-c', 'conda-forge', '-c', 'bioconda', 'gemini', 'cyvcf2', 'pip']' returned non-zero exit status 1
```

gemini --v show's i'm running 0.30.1

Any help is appreciated.

**Comment by brentp** [comment]
the permissions on your install are messed up. I would re-install from scratch.
Or maybe you can try `sudo chown -R $USER:$USER //usr/local/share/gemini/`

**Comment by kellogg76** [comment]
> the permissions on your install are messed up. I would re-install from scratch.
> Or maybe you can try `sudo chown -R $USER:$USER //usr/local/share/gemini/`

Thanks, but reinstalling from scratch with
`python gemini_install.py /usr/local /usr/local/share/gemini`

Gives another error.

```
/usr/local/share/gemini/anaconda/bin/gemini --annotation-dir /usr/local/share/gemini/gemini_data update --dataonly --tooldir /usr/local
Upgrading associated tools...
Traceback (most recent call last):
  File "/usr/local/share/gemini/anaconda/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1085, in update_fn
    gemini_update.release(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_update.py", line 34, in release
    config = gemini.config.read_gemini_config(args=args, allow_missing=True)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py", line 65, in read_gemini_config
    config["annotation_dir"] = args.annotation_dir
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "gemini_install.py", line 191, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 84, in main
    install_rest(gemini, args)
  File "gemini_install.py", line 149, in install_rest
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/gemini/anaconda/bin/gemini', '--annotation-dir', '/usr/local/share/gemini/gemini_data', 'update', '--dataonly', '--tooldir', '/usr/local']' returned non-zero exit status 1

```

Do you have any other suggestions on what I can try?

**Comment by kellogg76** [comment]
> It looks like that's the same error, you don't have permissions in /usr/local/share

I wondered that but my permissions for /usr/local/share are rwxrwxrwx, and I get the same error no matter where I try installing even though my account is Admin.

**Comment by YichaoOU** [comment]
same problem here
