### ISSUE TITLE
running setup.py install > RuntimeError: Python version >= 3.5 required

### ISSUE THREAD

**Issue by DanielAmsel** [arq5x/gemini#930]
Dear *,

I just tried to install gemini in an ubuntu 19.04 docker container.

I first installed the dependencies, I found:
`apt-get update && apt-get install -y wget python gcc zlib1g-dev tabix build-essential grabix bedtools git python-pip`

`pip install pybedtools`

I then pulled either the GIT repo or used the release v0.30.1

and ran :

`python setup.py install`

This lead to the error below, demanding a python3.5 or greater.

Someone has any ideas? I would be very thankful for help.

Best regards,
Daniel

```Reading https://pypi.org/simple/scipy/
Downloading https://files.pythonhosted.org/packages/cb/97/361c8c6ceb3eb765371a702ea873ff2fe112fa40073e7d2b8199db8eb56e/scipy-1.3.0.tar.gz#sha256=c3bb4bd2aca82fb498247deeac12265921fe231502a6bc6edea3ee7fe6c40a7a
Best match: scipy 1.3.0
Processing scipy-1.3.0.tar.gz
Writing /tmp/easy_install-TRZjRk/scipy-1.3.0/setup.cfg
Running scipy-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-TRZjRk/scipy-1.3.0/egg-dist-tmp-rSOxHw
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    'Topic :: Scientific/Engineering :: Bio-Informatics']
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 443, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 732, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 777, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-TRZjRk/scipy-1.3.0/setup.py", line 31, in <module>
    'static/third_party/bootstrap/css/*',
RuntimeError: Python version >= 3.5 required.```

**Comment by brentp** [comment]
Can you try running python gemini_install.py instead? That is the only reliable way to install.

**Comment by DanielAmsel** [comment]
Hi, thank you very much. I'll give it a try :)

**Comment by DanielAmsel** [comment]
Hi again.
the installer script seems to work :)
I, of course, had to add `sqlite3` to the installed packages.
This appeared when running the `master-test.sh`.

**Comment by brentp** [comment]
glad to hear it. thanks for following up.

**Comment by gmteunisse** [comment]
I'm also installing GEMINI into a ubuntu:18.04 docker image, and get the same error (see below). I'm following the instructions in the [Manual installation](https://github.com/arq5x/gemini/blob/master/docs/content/installation.rst#manual-installation) part of the installation guide. Is it no longer recommended to perform the manual installation?
